### ISSUE TITLE
Fa' attentzione alle e-mail di Travis CI se ci sono errori su questo tema di icone

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/gnome-plus#1]
Ciao @Bonandry !

Ho ricevuto molte e-mail di Travis CI, segnalando che c'era un errore sul tema di icone. Ha detto che l'icona `org.gnome.Taquin` aveva un'immagine incorporata. 

Ti ho chiamato per leggere le e-mail di Travis CI, ma sembra che non hai l'abitudine di leggere le e-mail. Perciò, ti chiamo qui.

Ma l'ho rimossa e corretta. Ho mosso l'immagine di Taquin, rimossa del file, per la cartella `images'.

Devi sapere che FreeDesktop GNOME non approva l'incorporazione dell'immagine sul file SVG. 

Se hai bisogno di quella immagine per l'icona di Taquin, crea l'oggetto irregolare con gradiente avanzato, imitando l'immagine.

**Comment by Bonandry** [comment]
non ho ricevuto nessuna email ì, chi è Travis CI?
![Schermata da 2019-04-16 07-42-53](https://user-images.githubusercontent.com/7957697/56184711-5ea89200-601b-11e9-9796-5fd7cdf78a03.png)
non trovo l'immagine incorporata
