### ISSUE TITLE
Use stock symbolic icons?

### ISSUE THREAD

**Issue by ripefig** [Bonandry/gnome-plus#11]
The Suru icons don't really fit with the gnome theme. Why not use the symbolic icons from Adwaita (as much as possible)?

**Comment by gusbemacbe** [comment]
Hi @ripefig,

We do not have the "stock" folder. Which folder are you referring to? 

In the new Adwaita theme, the most of symbolic icons in actions, panel and status are not new yet.

**Comment by ripefig** [comment]
Yeah, but I think the current ones fit still fit better than Suru, and I expect the new symbolic icons to be fairly similar to the current ones. 

The suru icons have a "high-tech" style that is very foreign to Adwaita.

**Comment by ripefig** [comment]
I'm referring to these icons. Aren't these Suru icons?

![image](https://user-images.githubusercontent.com/45201036/57195218-ca19bb80-6f58-11e9-84c8-84e0e12c470b.png)

**Comment by gusbemacbe** [comment]
Hi @ripefig !

These icons belong to the folder "places". I agree with you that these icons are too Suru for GNOME++. I will talk wirh @Bonandry and suggest him to replace them for purely Adwaita. Let's see his decision.

**Comment by gusbemacbe** [comment]
@Bonandry 

Ti suggeriamo di sostituire le icone di 16px e symbolic della cartella «places» allo stile di Suru per quelle allo stile puro d’Adwaita perché queste icone sono troppo Suru per l’Adwaita/GNOME++

**Comment by gusbemacbe** [comment]
@Bonandry 

E ricorda di non aggiornare la branch/versione `master`. Solamente la versione `beta`.

Rimuove la cartella `gnome-plus` e apri il terminale:

```
cd ~/Documenti/GitHub
git clone -b beta --single-branch https://github.com/Bonandry/gnome-plus
```

**Comment by Bonandry** [comment]
fatto, ho messo anche alcune icone alternative che non ho mai trovato in svg e che ho fatto partendo da 0

**Comment by ripefig** [comment]
I am not sure if this is relevant @gusbemacbe, but  here are some extra symbolic icons for apps: https://store.kde.org/p/1303977/

**Comment by gusbemacbe** [comment]
Hi @ripefig !

@Bonandry has already updated the icons, but they are in the private repository. The next weeks we must release. 

Are these Focus Icons derived from Adwaita icons?

**Comment by ripefig** [comment]
No, they are not. So use with caution.

**Comment by gusbemacbe** [comment]
Hi @ripefig !

Please test the beta branch of GNOME++ if they are really purely Adwaita.

**Comment by gusbemacbe** [comment]
Hi @ripefig 

I have just upstreamed it. Finally, most of icons have been reimaged with pure Adwaita look, but actions icons are taken from Papirus actions icons.

**Comment by gusbemacbe** [comment]
I have just released it officially. You can download it now.
