### ISSUE TITLE
ICONE 32

### ISSUE THREAD

**Issue by Bonandry** [Bonandry/gnome-plus#12]
Love this theme! Unfortunately it doesn't play nice with Dash to Dock with the icon size smaller than 32. Now i have the tray style icons in the panel and i can't barely see it. 
questo chiede un utente su opendesktop

in svg non so come fare ma ho fatto una cartella con tutte le icone APP in PNG a 32 
ma non so se può funzionare

**Comment by Bonandry** [comment]
![Schermata da 2019-05-06 19-25-39](https://user-images.githubusercontent.com/7957697/57242839-decb8180-7034-11e9-8afb-a2dba4875d44.png)

**Comment by gusbemacbe** [comment]
@Bonandry 

> Love this theme! Unfortunately it doesn't play nice with Dash to Dock with the icon size smaller than 32. Now i have the tray style icons in the panel and i can't barely see it.

Vado parlare con lui. 

> in svg non so come fare ma ho fatto una cartella con tutte le icone APP in PNG a 32
ma non so se può funzionare

Le icone in SVG, JPG o PNG funzionano sempre. Ma JPG e PNG non sono buone per i computer con uno schermo retina.

Non hai bisogno di fare niente. Vado esplicare all'utenti come fare se egli vuoi le icone colorite in 16 e 32 px.

**Comment by gusbemacbe** [comment]
Gli ho appena esplicato, @Bonandry .
