### ISSUE TITLE
minor coloration issue

### ISSUE THREAD

**Issue by Mumrik93** [Bonandry/gnome-plus#15]
Love the new update, the coloured icons look great! I have an issue thou, mostly minor, but some of the icons have a bit of a color issue, a few are very bright while some are unusually dark.

I took a screenshot of my desktop while using the icons. You can see that the trash bin is Very dark, whilst the Mailspring (my mail client) is very bright. Lastly on the right side of my panel you can see the f.lux icon is very dark, whilst all other icons are a nicely (and clear) white.
No major issue, but they are issues that might nag people (me included) in the long run.

![Skärmbild från 2019-05-18 00-43-53](https://user-images.githubusercontent.com/7977697/57960250-05789a80-7908-11e9-8a6a-b40e8a72afbc.png)
![Skärmbild från 2019-05-18 00-57-31](https://user-images.githubusercontent.com/7977697/57960251-07425e00-7908-11e9-9215-37b9144115f1.png)

**Comment by gusbemacbe** [comment]
Hej och god kväll @Mumrik93 !

I could see the flux and trash icons, I will fix them.

But I did not see the Mailspring icon, are you referring to yellow-and-white icon, byside Discord and Telegram?

**Comment by Bonandry** [comment]
@gusbemacbe nella versione BETA ho colorato in bianco le icone del pannello e una nuova icona cestino

**Comment by Mumrik93** [comment]
Tjenare och go'middag @gusbemacbe 
It sure is. I think the stock Mailspring icon would fit pretty well into the GNOME++ theme (not that the current one wont work either, if only the brightness was turned down a little bit)

Ps: did not think of this before, but a Steam-folder would be nice too, completely unnecessary but would pretty nice to have.

Pps: The update-icon in the system-tray is still the stock one, it would be pretty cool if you used another one, the stock one is pretty boring to be honest. The Papirus and Korla icon-themes have a really nice system-tray icons for the updater. (reference the first pic i uploaded, it uses the papirus system-tray icon, while the second pic uses the Gnome++ icon)

**Comment by gusbemacbe** [comment]
> It sure is. I think the stock Mailspring icon would fit pretty well into the GNOME++ theme (not that the current one wont work either, if only the brightness was turned down a little bit)

I will explain to @Bonandry .

@Bonandry , per favore, dobbiamo ridisegnare un'icona specifica per Mailspring. Utilizza i colori con forme di blu. Le forme di bianco devono esse **meno** luminose.

> Ps: did not think of this before, but a Steam-folder would be nice too, completely unnecessary but would pretty nice to have.

We will add a new folder. My [Suru++ 30](https://github.com/gusbemacbe/suru-plus) and @Bonandry's [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu) have a Steam folder. 

@Bonandry , andiamo creare una nuova icona di `places` con il nome di `folder-steam`.

> Pps: The update-icon in the system-tray is still the stock one, it would be pretty cool if you used another one, the stock one is pretty boring to be honest. The Papirus and Korla icon-themes have a really nice system-tray icons for the updater. (reference the first pic i uploaded, it uses the papirus system-tray icon, while the second pic uses the Gnome++ icon)

Are you suggesting we use purely GNOME system-tray icon or Papirus icon?

If you want Papirus system-tray icons, I will talk with @Bonandry and he will decide. My [Suru++ 30](https;//github.com/gusbemacbe/suru-plus) follows the Papirus philosophy and style, it uses Papirus system-tray icons, the difference between Suru++ and Papirus is that, Papirus is flat and Suru++ is cyberpunk and futuristic. 

Tack så mycket for your answer!

**Comment by Bonandry** [comment]
added mailspring folder-steam in gnome beta

**Comment by gusbemacbe** [comment]
@Mumrik93 

Here are new icons of Mailspring and Steam folder:

<img src="https://user-images.githubusercontent.com/2257024/57971028-11dc1200-795f-11e9-8117-3ba6876e30ec.png" alt="folder steam" height="128px" />

<img src="https://user-images.githubusercontent.com/2257024/57971042-3637ee80-795f-11e9-8da7-d4194ecd3ad4.png" alt="mailspring" height="128px" />

Did you like them?

**Comment by Mumrik93** [comment]
Hello again, no no i did not mean that you would copy the system-tray icons from papirus, i meant specifically the "update-icon" in the system-tray. It still uses the stock icon, which looks a bit out-of-place

**Comment by Mumrik93** [comment]
@gusbemacbe Oh those looks beautiful <3 Please use them!

**Comment by gusbemacbe** [comment]
@Mumrik93 

I got it. GNOME++ does not have this icon. I will search for Papirus update icons to get missed icons.

**Comment by Mumrik93** [comment]
I just found out that also the caffeine indicator (in the system-tray) is unusually dark, just like the f.lux icon. Maybe there are more icons then that who's very dark?

![Skärmbild från 2019-05-18 21-23-58](https://user-images.githubusercontent.com/7977697/57974129-8e98db80-79b3-11e9-8efd-fbdd9875d8ef.png)

**Comment by gusbemacbe** [comment]
Hej @Mumrik93 !

The most of updated icons and several improved icons are in the private repository. As there are not new ideas, I must pull upstream it to this repository in the branch `beta` tomorrow. Why tomorrow? Because @Bonandry and I need to symlink many similiar icons to optimise the pack size.

**Comment by gusbemacbe** [comment]
Tjenare och go'middag @Mumrik93 

I have just upstreamed it to the beta branch.

**Comment by gusbemacbe** [comment]
Hej, I have just released it officially. You can download now with these fixed problems.
