### ISSUE TITLE
Gnome Disks with wrong icon

### ISSUE THREAD

**Issue by Phraqzy** [Bonandry/gnome-plus#16]
Gnome Disks shows a joystick icon as in the screenshots below:

Panel
![image](https://user-images.githubusercontent.com/43043436/58719001-1532bd00-83a5-11e9-9ca2-27420afcd4e0.png)

Alacarte
![image](https://user-images.githubusercontent.com/43043436/58719043-30053180-83a5-11e9-9185-652e23a7fabf.png)

**Comment by Bonandry** [comment]
check the name of the icon, it works fine for me
![Schermata da 2019-05-31 18-12-57](https://user-images.githubusercontent.com/7957697/58719469-0ad9e880-83d0-11e9-9140-e65b11fa9ff0.png)

**Comment by Phraqzy** [comment]
For some reason, this problem occur only with this icon theme

**Comment by gusbemacbe** [comment]
@Phraqzy 

Finally I have found the problem. I will fix it:

![image](https://user-images.githubusercontent.com/2257024/58734737-a10d0f00-83ce-11e9-94d4-16996d8e2da4.png)

**Comment by gusbemacbe** [comment]
I have just fixed it. I will upstream the private repository to this beta branch.

**Comment by gusbemacbe** [comment]
I have just upstreamed it into the beta branch.

**Comment by gusbemacbe** [comment]
I have just released it officially. You can download now with this fixed problem.
