### ISSUE TITLE
[Icon request] 66 missed icons

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#18]
- [x] **Qt Assistant**
Comment=Shows Qt documentation and examples
Icon=assistant
[Icon Link](http://www.iconarchive.com/show/captiva-icons-by-bokehlicia/QtProject-assistant-icon.html)

- [x] **balenaEtcher**
Comment=Flash OS images to SD cards and USB drives, safely and easily.
Icon=balena-etcher-electron
[Icon Link](https://github.com/balena-io/etcher/blob/master/assets/icon.png)

- [x] **ClipGrab**
Comment=Download videos and convert it
Icon=clipgrab
[Icon Link](https://clipgrab.org)

- [x] **CMake**
Comment=Cross-platform buildsystem
Icon=CMakeSetup
[Icon Link](https://cmake.org/wp-content/uploads/2018/11/cmake_logo_slider.png)

- [x] **Code::Blocks IDE**
Comment=Configurable and extensible IDE
Icon=codeblocks
[Icon Link](https://icon-icons.com/icon/codeblocks/104542)

- [x] **Sequeler**
Comment=Friendly SQL Client
Icon=com.github.alecaddd.sequeler
[Icon Link](https://github.com/Alecaddd/sequeler/blob/master/data/assets/icons/128x128/com.github.alecaddd.sequeler.svg)

- [x] **Taxi**
Comment=Transfer local and remotes files
Icon=com.github.alecaddd.taxi
[Icon Link](https://github.com/Alecaddd/taxi/blob/master/data/icons/128.svg)

- [x] **Gitignore**
Comment=Gitignore reference for various languages
Icon=com.github.arshubham.gitignore
[Icon Link](https://github.com/arshubham/gitignore/blob/master/data/images/icons/128/com.github.arshubham.gitignore.svg)

- [x] **Hash It**
Comment=Generate and verify file hashes
Icon=com.github.artemanufrij.hashit
[Icon Link](https://github.com/artemanufrij/hashit/blob/master/data/icons/64/com.github.artemanufrij.hashit.svg)

- [x] **Vala Tester**
Comment=Test some Vala code!
Icon=com.github.bartzaalberg.vala-tester
[Icon Link](https://github.com/bartzaalberg/vala-tester/blob/master/data/icons/128/com.github.bartzaalberg.vala-tester.svg)

- [x] **ValaCompiler**
Comment=A simple GUI for valac
Icon=com.github.basjam.valacompiler
[Icon Link](https://github.com/basjam/ValaCompiler/blob/master/data/icons/128/com.github.basjam.valacompiler.svg)

- [x] **VServer**
Comment=Open an http server in the selected folder and share your files.
Icon=com.github.bcedu.valasimplehttpserver
[Icon Link](https://github.com/bcedu/ValaSimpleHTTPServer/blob/master/data/icons/com.github.bcedu.valasimplehttpserver.svg)

- [x] **Copy Paste Grab**
Comment=Download videos from hundreds of websites
Icon=com.github.cryptowyrm.copypastegrab
[Icon Link](https://github.com/cryptowyrm/copypastegrab/blob/master/data/icons/128/com.github.cryptowyrm.copypastegrab.svg)

- [x] **Formatter**
Comment=Format devices
Icon=com.github.djaler.formatter
[Icon Link](https://github.com/Djaler/Formatter/blob/master/data/icons/com.github.djaler.formatter.svg)

- [x] **EasySSH**
Comment=Manage your ssh connections
Icon=com.github.muriloventuroso.easyssh
[Icon Link](https://github.com/muriloventuroso/easyssh/blob/master/data/icons/128/com.github.muriloventuroso.easyssh.svg)

- [x] **Resizer**
Comment=Image resizer
Icon=com.github.peteruithoven.resizer
[Icon Link](https://github.com/peteruithoven/resizer/blob/master/data/icons/128.svg)

- [x] **Minder**
Comment=Create, develop and visualize your ideas
Icon=com.github.phase1geo.minder
[Icon Link](https://github.com/phase1geo/Minder/blob/master/data/icons/128/com.github.phase1geo.minder.svg)

- [x] **Notes-Up**
Comment=Your markdown notebook
Icon=com.github.philip-scott.notes-up
[Icon Link](https://github.com/Philip-Scott/Notes-up/blob/master/data/icons/64/com.github.philip-scott.notes-up.svg)

- [x] **Spice-Up**
Comment=Spice up your slides
Icon=com.github.philip-scott.spice-up
[Icon Link](https://github.com/aljelly/Spice-up/blob/new-icons/data/icons/64/com.github.philip-scott.spice-up.svg)

- [x] **Raddiu**
Comment=Listen to web radios
Icon=com.github.ranfdev.raddiu
[Icon Link](https://github.com/ranfdev/raddiu/blob/master/data/icons/128/com.github.ranfdev.raddiu.svg)

- [x] **Mindi**
Comment=A simple Video to Audio converter
Icon=com.github.torikulhabib.mindi
[Icon Link](https://github.com/torikulhabib/mindi/blob/master/data/icons/128.svg)

- [x] **Spectator**
Comment=REST Client
Icon=com.github.treagod.spectator
[Icon Link](https://github.com/treagod/spectator/blob/master/data/icons/128x128/com.github.treagod.spectator.svg)

- [x] **Manage Printing**
Comment=CUPS Web Interface
Icon=cups
[Icon Link](http://www.iconarchive.com/show/oxygen-icons-by-oxygen-icons.org/Status-printer-printing-icon.html)

- [x] **Qt Designer**
Comment=Design GUIs for Qt applications
Icon=QtProject-designer
[Icon Link]()

- [x] **EDuke32**
Comment=Advanced Duke Nukem 3D engine
Icon=eduke32
[Icon Link](https://i.imgur.com/xdi3t44.png)

- [x] **Electron 2**
Icon=electron2
[Icon Link](https://raw.githubusercontent.com/atom/electron/master/atom/browser/resources/win/atom.ico)

- [x] **Electron**
Icon=electron
[Icon Link](https://raw.githubusercontent.com/atom/electron/master/atom/browser/resources/win/atom.ico)

- [x] **EmulationStation**
Comment=Emulationstation
Icon=emulationstation
[Icon Link](https://digimoot.files.wordpress.com/2018/08/retropie-setup-ubuntu-or-mint1.png)

- [x] **HandBrake**
Comment=Transcodes DVD, Bluray, and other media
Icon=fr.handbrake.ghb
[Icon Link](http://erichansen.tv/wp-content/uploads/2013/01/HandBrake-icon.jpg)

- [x] **GdaBrowser**
Comment=Browse your database's contents
Icon=gda-browser-5.0
[Icon Link](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/gda-browser-5.0-icon.html)

- [x] **Gda Control Center**
Comment=Configure your database access environment
Icon=gda-control-center
[Icon Link](https://c7.uihere.com/files/294/418/482/database-administrator-computer-icons-clip-art-maintenance-equipment-thumb.jpg)

- [x] **Grub Customizer**
Comment=Customize the bootloader (GRUB2 or BURG)
Icon=grub-customizer
[Icon Link](http://tipsonubuntu.com/wp-content/uploads/2016/10/grub-customizer-icon.jpg)

- [x] **GTK+ Demo**
Comment=GTK+ code examples and demonstrations
Icon=gtk3-demo
[Icon Link](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/gtk3-demo-icon.html)

- [x] **HP Device Manager**
Comment=View device status, ink levels and perform maintenance.
Icon=hp_logo
[Icon Link]()

- [x] **Insomnia**
Comment=Debug APIs like a human, not a robot
Icon=insomnia
[Icon Link](http://icons.iconarchive.com/icons/papirus-team/papirus-apps/256/insomnia-icon.png)

- [x] **IntelliJ IDEA**
Comment=The Drive to Develop
Icon=intellij
[Icon Link](https://iconscout.com/icon/intellij-idea)

- [x] **Klavaro**
Comment=A very flexible and efficient touch typing tutor.
Icon=klavaro
[Icon Link](https://github.com/cbrnix/Newaita/blob/master/Newaita/apps/64/klavaro.svg)

- [x] **Koala**
Comment=A cool tool for web developers
Icon=koala
[Icon Link](https://github.com/oklai/koala/blob/master/assets-linux/icons/hicolor/128x128/apps/koala.png)

- [x] **Lightworks**
Comment=Cross-platform film & video editor
Icon=lightworks
[Icon Link](https://screenshots.en.sftcdn.net/en/scrn/318000/318077/54bd277193daescr_1421675328-535x535.png)

- [x] **Qt Linguist**
Comment=Add translations to Qt applications
Icon=linguist
[Icon Link]()

- [x] **MySQL Workbench**
Comment=MySQL Database Design, Administration and Development Tool
Icon=mysql-workbench
[Icon Link](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/mysql-workbench-icon.html)

- [x] **FeedReader**
Comment=Read feeds from web services
Icon=org.gnome.FeedReader
[Icon Link](https://github.com/jangernert/FeedReader/blob/master/data/application-icons/hicolor/128x128/apps/org.gnome.FeedReader.svg)

- [x] **Pomodoro**
Comment=A simple time management utility
Icon=gnome-pomodoro
[Icon Link](http://gnomepomodoro.org/images/icons/256x256.png)

- [x] **pCloud**
Comment=pCloud Drive Client built using electron and node.js. Distributed with AppImage.
Icon=pcloud
[Icon Link](https://icons8.com.br/icon/91483/pcloud)

- [x] **pgAdmin 4**
Comment=PostgreSQL Tools
Icon=pgAdmin4
[Icon Link](https://kiahosseini.github.io/assets/image/pgadmin4_install/pgadmin.svg)

- [x] **Plank**
Comment=Stupidly simple.
Icon=plank
[Icon Link](http://ubuntuhandbook.org/wp-content/uploads/2017/03/plank-dock245.png)

- [x] **PlayOnLinux**
Comment=Front-end application for the wine
Icon=playonlinux
[Icon Link](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/playonlinux-icon.html)

- [x] **Popcorn Time**
Comment=Watch Movies and TV Shows instantly
Icon=popcorntime
[Icon Link](https://commons.wikimedia.org/wiki/File:Popcorn_Time_logo.png)

- [x] **Qt QDbusViewer**
Comment=Debug D-Bus applications
Icon=qdbusviewer
[Icon Link]()

- [x] **QEMU**
Comment=Allow testing Video4Linux devices
Icon=qemu
[Icon Link](https://qemu.weilnetz.de/icon/benoit/black_and_orange_qemu_head-128x128.png)

- [x] **Qt V4L2 test Utility**
Comment=Allow testing Video4Linux devices
Icon=qv4l2
[Icon Link]()

- [x] **Qt V4L2 video capture utility**
Comment=Viewer for video capture
Icon=qvidcap
[Icon Link]()

- [x] **RetroArch**
Comment=Frontend for emulators, game engines and media players
Icon=retroarch
[Icon Link](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/retroarch-icon.html)

- [x] **Riot**
Comment=A feature-rich client for Matrix.org
Icon=riot
[Icon Link](https://raw.githubusercontent.com/vector-im/riot-web/develop/electron_app/img/riot.ico)

- [x] **Robo 3T**
Comment=Shell-centric MongoDB management tool
Icon=robo3t
[Icon Link](https://raw.githubusercontent.com/Studio3T/robomongo/master/src/robomongo/gui/resources/icons/logo-256x256.png)

- [x] **Rygel Preferences**
Icon=rygel
[Icon Link]()

- [x] **SmartGit**
Comment=Graphical Git/Hg client
Icon=smartgit
[Icon Link](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/smartgit-icon.html)

- [x] **StarUML**
Comment=A sophisticated software modeler
Icon=staruml
[Icon Link](http://staruml.io/image/staruml_logo.png)

- [x] **SVG Cleaner**
Comment=Batch, tunable SVG cleaning program
Icon=svgcleaner
[Icon Link](https://github.com/RazrFalcon/svgcleaner-gui/blob/master/icons/svgcleaner.ico)

- [x] **TeXstudio**
Comment=LaTeX development environment
Icon=texstudio
[Icon Link](https://cn.opendesktop.org/cache/85x85-crop/img/2/9/c/5/ca8e3c6bab236d6e98a8fa534dd76d68d3b4.png)

- [x] **uGet**
Comment=Download multiple URLs and apply it to one of setting/queue.
Icon=uget-icon
[Icon Link](http://www.iconarchive.com/show/flatwoken-icons-by-alecive/Apps-Uget-icon.html)

- [x] **UXTerm**
Comment=xterm wrapper for Unicode environments
Icon=xterm-color_48x48
[Icon Link]()

- [x] **Wine Windows Program Loader**
Icon=wine
[Icon Link]()

- [x] **XTerm**
Comment=standard terminal emulator for the X window system
Icon=xterm-color_48x48
[Icon Link](https://invisible-island.net/xterm/images/icons-xterm-color_226.png)

- [x] **Zenmap**
Comment=A cross-platform GUI for the Nmap Security Scanner.
Icon=zenmap
[Icon Link](http://www.iconarchive.com/show/flatwoken-icons-by-alecive/Apps-Zenmap-icon.html)

Thanks in advance!

**Comment by gusbemacbe** [comment]
@btd1337 

Algumas ícones foram aderidas na versão/branch `beta`, mas demais ícones serão aderidas ao repositório privado e farei upstream do privado para o público.

Não te esqueças de ler meu comentário no teu novo repositório.

**Comment by gusbemacbe** [comment]
Hey @btd1337 

>     * [x]  **HP Device Manager**
>       Comment=View device status, ink levels and perform maintenance.
>       Icon=hp_logo
>       Icon Link

O ícone de HP é predefinido ou codificado fixamente. Tens de modiifcar manualmente o caminho de ícone, tornando-o codificado suavemente.

**Comment by btd1337** [comment]
> Hey @btd1337
> 
> > ```
> > * [x]  **HP Device Manager**
> >   Comment=View device status, ink levels and perform maintenance.
> >   Icon=hp_logo
> >   Icon Link
> > ```
> 
> O ícone de HP é predefinido ou codificado fixamente. Tens de modiifcar manualmente o caminho de ícone, tornando-o codificado suavemente.

Eu utilizo o `harcode-fixer`.

**Comment by btd1337** [comment]
@gusbemacbe Algumas observações:

- O ícone do ClipGrab não está correto. Ele é um gerenciador de download de vídeos e não um editor de textos.

- As aplicações Electron e Electron2, infelizmente tem o mesmo nome para o sistema. Utilizar o mesmo ícone, torna impossível distinguí-las. É possível usar tonalidades diferentes pra uma das versões?

- A aplicação Gitignore faz o oposto que uma aplicação Git comum. Sendo assim, usar o mesmo ícone de aplicações Git, também confunde com seu propósito. É possível, pelo menos usar uma cor diferente? Roxo por exemplo.

Seria possível corrigir estes detalhes? Obrigado desde já.

**Comment by gusbemacbe** [comment]
> O ícone do ClipGrab não está correto. Ele é um gerenciador de download de vídeos e não um editor de textos.

Vou corrigi-lo agora.

> As aplicações Electron e Electron2, infelizmente tem o mesmo nome para o sistema. Utilizar o mesmo ícone, torna impossível distinguí-las. É possível usar tonalidades diferentes pra uma das versões?

Preciso pesquisar e ver os ícones antigos do Electron – versão 2 e nova versão. 

> A aplicação Gitignore faz o oposto que uma aplicação Git comum. Sendo assim, usar o mesmo ícone de aplicações Git, também confunde com seu propósito. É possível, pelo menos usar uma cor diferente? Roxo por exemplo.

Vou mudar de cor agora.

**Comment by gusbemacbe** [comment]
Pronto, ficaram melhores?

**Comment by btd1337** [comment]
@gusbemacbe Ficou ótimo! Parabéns pelo bom trabalho.

**Comment by Bonandry** [comment]
add icons 
balena-etcher-electron
cmake
codeblocks
com.github.alecaddd.sequeler
wine
winetricks

**Comment by Bonandry** [comment]
add 
com.github.artemanufrij.hashit 
com.github.bartzaalberg.vala-tester 
com.github.basjam.valacompiler

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Sempre ti ricordi di scrivere `#18` alla fine del messagio o della descrizione.

**Comment by Bonandry** [comment]
add xterm-color_48x48-symbolic #18

**Comment by btd1337** [comment]
Where I find this updates?

**Comment by gusbemacbe** [comment]
Oi @btd1337, os novos ícones estão no repositório privado por razão de proteção contra aproveitadores. Como não temos ideias, hoje farei upstream do repositório privado para este repositório público.

Já ensinei o Andrea a utilizar a referência (número deste tópico) na mensagem do commit sem precisar fazer novos comentários neste tópico, pois as referências são automaticamente adicionadas a este tópico.

**Comment by gusbemacbe** [comment]
Pronto, mas ainda vamos fazer mais ícones.

Desculpe-me, eu tive um imprevisto.

**Comment by Bonandry** [comment]
completato, tutte le icone pronte

**Comment by gusbemacbe** [comment]
@btd1337, não baixe agora. Andrea fez um pouquinho errado. Vou corrigir e reajustar tudo. Espera, que termino tudo hoje.

**Comment by gusbemacbe** [comment]
Pronto, @btd1337 . 

Vou corrigir a ausência de `places/scalable`, em referência ao outro tópico.

**Comment by btd1337** [comment]
@Bonandry Mille grazie per il tuo ottimo lavoro!

**Comment by Bonandry** [comment]
@btd1337 Grazie a te!!
