### ISSUE TITLE
Bug in Folders - Dark Theme

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#19]
When the theme Dark is set, see like are the folders:

![Captura de tela de 2019-06-05 22-25-17](https://user-images.githubusercontent.com/11943860/59000496-259dca00-87e1-11e9-82a0-c3c81edfb6bb.png)

**Comment by gusbemacbe** [comment]
Olá @btd1337 !

Andrea não faz temas escuros. Quem assume a construção de temas escuros sou eu. Mas se estás muito apressado, preparo-te os comandos:

```bash
cd GNOME++-Dark
sed --in-place --follow-symlinks 's/#e6ddff\|#241f31/#444444/g' **/places/*.svg
```

**Comment by btd1337** [comment]
Correção do comando: 

`sed --in-place --follow-symlinks 's/#e6ddff\|#241f31/#444444/g' ./places/**/*.svg`

PS: A pasta places/scalable está faltando, vocês usam symlink pro tema padrão?


![Captura de tela de 2019-06-06 02-57-55](https://user-images.githubusercontent.com/11943860/59010230-ef734100-8806-11e9-8733-57845675b2af.png)

**Comment by gusbemacbe** [comment]
> PS: A pasta places/scalable está faltando, vocês usam symlink pro tema padrão?

Agora estou ciente de a pasta `scalable` estar ausente no GNOME++ Escuro, vou corrigir. Se estás apressado, executa. 

```bash
ln -sfnr GNOME++/apps/scalable GNOME++-Dark/apps/scalable
```

Observa que GNOME++ Escuro é designado para o ambiente plenamente escuro. Para ambiente claro mas com panéis e barras de lado escuras, como o caso do Nautilus com tema de GTK Telinkrin, então primeiramente tenho de conversar com o Andrea se ele me deixa fazer para as distribuições não-Ubuntu (por exemplo, elementary OS e Linux Mint).

**Comment by gusbemacbe** [comment]
Não, errei, vi que a [pasta `scalable` está presente](https://github.com/Bonandry/gnome-plus/blob/master/GNOME%2B%2B-Dark/apps/scalable) là. Sim, utilzamos ligações simbólicas. Mas vou verificar.

**Comment by btd1337** [comment]
@gusbemacbe Aqui não está presente: https://github.com/Bonandry/gnome-plus/tree/master/GNOME%2B%2B-Dark/places

**Comment by gusbemacbe** [comment]
Muito obrigado por ter conseguido descobrir. Pensei que fosse no `apps`. No fim de semana, corrigirei e faremos mais íconos porque estou a tentar resolver os problemas no Arch Linux.

Não sei se ainda estás a utilizar Arch Linux porque tu me reportaste um problema de Suru++ Telinkrin no Arch Linux. Se sim, dá uma olhada: https://plus.diolinux.com.br/t/habilitar-kms-para-as-placas-intel-aceleracao-no-chromium-e-habilitar-o-modulo-i915-mas-quero-saber-se-o-que-estou-a-fazer-e-certo-ou-errado/5047

**Comment by gusbemacbe** [comment]
Pronto, @btd1337 !

Por favor, transfere a branch `beta`, testa com novos ícones e com nova pasta `places/scalable`. Caso funcione, avisa-me que vou fazer pull request da branch `beta` para branch official.

**Comment by btd1337** [comment]
As pastas foram corrigidas. Percebi que alguns ícones também estão ausentes na versão dark, por exemplo o da Lixeira, dentre outros. Poderia usar symlink da pasta de Apps entre a versão dark e a original.

**Comment by gusbemacbe** [comment]
Vou investigar.

**Comment by gusbemacbe** [comment]
Desuclpe-me pela minha ausência, é que eu tinha estado muito ocupado e tinha de esperar receber o meu novo monitor. 

Todos os ícones de lixeira foram adicionados a ambos os temas normal e escuro, mas não sei quais outros ícones tu disseste.

**Comment by btd1337** [comment]
@gusbemacbe Eu testei e por enquanto me parece que ficou tudo ok. Pode mergear a branch Beta e fechar esta issue! Novamente, muito obrigado por este excelente trabalho!

**Comment by btd1337** [comment]
Estes ícones simbólicos devem ser rosa mesmo?

Estão do mesmo jeito que as pastas...

![Captura de tela de 2019-06-22 13-21-02](https://user-images.githubusercontent.com/11943860/59966284-a9013000-94f0-11e9-80b1-c140b82958d8.png)

**Comment by gusbemacbe** [comment]
Vou ver por que o tema não está a utilizar os ícones coloridos nessa janela pop-up. Estás a utilizar Unity no Arch Linux?

**Comment by gusbemacbe** [comment]
Concluí que o problema está no `index.theme`. Vou testar com o `index.theme` do Suru++.

**Comment by gusbemacbe** [comment]
Então a culpa não foi do `index.theme` e sim das heranças das pastas. As pastas `24`e `32` herdam da pasta `16`, @btd1337.

Mas tenho de pedir autorização para @Bonandry se posso herdar novamente a pasta `scalable` às pastas `24` e `32` e criar a nova pasta `22`.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Vedi l'ultima immagine, perché le cartelle `24` e `32` sono ereditate dalla cartella `16`, e non dalla cartella `scalable`. Posso ereditare nuovamente le cartelle `24` e `32` alla cartella `scalable` e creare la nuova cartella `22`? Solamente nelle cartelle `apps`, `mimetypes` e `places`. E posso correggere il file `index.theme`?

**Comment by Bonandry** [comment]
Ciao @gusbemacbe, certo

**Comment by btd1337** [comment]
@gusbemacbe Não uso Unity. Uso o Gnome.

**Comment by gusbemacbe** [comment]
@btd1337, OK, como @Bonandry me autorizou, vou corrigir, mas primeiramente vou fazer os ícones que acabaste de pedir noutro tópico.

**Comment by gusbemacbe** [comment]
Pronto, por favor, testa.

**Comment by btd1337** [comment]
@gusbemacbe Acredito que o problema não é este que você tem mente. Aparentemente o tema foi projetado para ter ícones simbólicos nestes casos. Veja que em todos os outros casos o problema continua:

![Captura de tela de 2019-06-25 13-35-26](https://user-images.githubusercontent.com/11943860/60116558-a69c1180-974e-11e9-9326-e3d682285f0f.png)

![Captura de tela de 2019-06-25 13-34-56](https://user-images.githubusercontent.com/11943860/60116559-a69c1180-974e-11e9-80f1-52dd0e67cdb1.png)

![Captura de tela de 2019-06-25 13-39-00](https://user-images.githubusercontent.com/11943860/60116566-abf95c00-974e-11e9-8358-12da75270511.png)

![Captura de tela de 2019-06-25 13-44-33](https://user-images.githubusercontent.com/11943860/60117051-b5cf8f00-974f-11e9-93b9-bf2a1900de06.png)


A solução que usou, realmente usa os ícones maiores, mas veja como isso destoa do restante do tema e não fica bom. Os ícones ficam grandes demais e o contexto de todos os outros lugares continua usando os simbólicos.

![Captura de tela de 2019-06-25 13-40-19](https://user-images.githubusercontent.com/11943860/60116662-dfd48180-974e-11e9-9814-745fd6f9d103.png)

Acredito que o correto é aplicar uma cor escura a estes ícones que até então estão com a cor rosa. E se possível desfazer a mudança nas pastas 24 e 32, voltando a usar ícones no estilo simbólico.

**Comment by gusbemacbe** [comment]
Oi, @btd1337! Ainda estou confuso. Qual um dos três temas da família GNOME++: GNOME++, GNOME++ Escuro ou GNOME++ Colorido?

**Comment by btd1337** [comment]
A issue é sobre o tema escuro, todas as imagens são do tema escuro. Somente na janela ABRIR COM teve alteração pros ícones escaláveis, devido a última modificação que fez. Mas não ficou bom. Acredito que a solução correta é fazer os ícones simbólicos serem pretos ao invés de rosa.

**Comment by gusbemacbe** [comment]
Oi @btd1337 !

O GNOME++ Escuro é designado para utilizadores do ambiente gráfico **cheiamente** escuro. Por isso, criei GNOME++ Claro, inspirado pelo Papirus Light do @SmartFinn hoje.

Testa se GNOME++ Claro é o que tu queres excatamente.

**Comment by btd1337** [comment]
@gusbemacbe acertou em cheio! Era isso mesmo que eu tinha em mente. Muito obrigado! Parabéns pelo seu ótimo serviço!

**Comment by gusbemacbe** [comment]
óptimo, vou finalizar o projecto e lançá-lo hoje.

**Comment by gusbemacbe** [comment]
@btd1337 , por favor, utiliza o teu projecto para enviar a lista de ícones perdidos no meu projecto [Suru++](https://github.com/gusbemacbe/suru-plus).
