### ISSUE TITLE
L'icona GwenView è troppo realistica per il semplice GNOME++

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/gnome-plus#2]
L'icona [GwenView](https://github.com/Bonandry/gnome-plus/commit/4781fbcba952d337347a0174391cd31800aaf7c4#diff-394a6ae67f8d57ede29931514f52f28d) è troppo realistica per il tema di icone GNOME++. Credo che hai bosgno di migliorarla.

**Comment by gusbemacbe** [comment]
![image](https://user-images.githubusercontent.com/2257024/56311641-ed550600-6124-11e9-8b8a-e80e92fa59f2.png)

Esse dovrebbero essere in stessa forma.

**Comment by Bonandry** [comment]
ho corretto

**Comment by gusbemacbe** [comment]
Perfetto! 

In reference to 4781fbc.
