### ISSUE TITLE
Request Icons

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#20]
- [x] **CMake**
Comment=Cross-platform buildsystem
Icon=CMakeSetup
[Icon Link](https://www.iconspng.com/image/37481/cmake)

- [x] **Configurator**
Comment=System-Settings editor.
Icon=configurator
[Icon Link](https://github.com/cassidyjames/configurator/blob/master/data/128/com.github.cassidyjames.configurator.svg)

- [x] **Quilter**
Comment=An Markdown Reader
Comment[it]=Un lettore Markdown
Icon=com.github.lainsce.quilter
[Icon Link](https://github.com/lainsce/quilter/blob/master/data/icons/128/com.github.lainsce.quilter.svg)

- [x] **quickDocs**
Comment=A fast developer docs reader that supports Valadoc and DevDocs
Comment[it]=Un veloce lettore di documenti per sviluppatori che supporta Valadoc e DevDocs
Icon=com.github.mdh34.quickdocs
[Icon Link](https://github.com/mdh34/quickDocs/blob/master/data/icons/128/com.github.mdh34.quickdocs.svg)

- [x] **Crow Translate**
Comment=A simple and lightweight translator that allows to translate and speak the selected text using the Google Translate API and much more
Icon=crow-translate
[Icon Link](https://github.com/crow-translate/crow-translate/blob/master/dist/unix/generic/hicolor/72x72/apps/crow-translate.png)

- [x] **Pomodoro**
Comment=A simple time management utility
Comment[it]=Una semplice utility per la gestione del tempo
Icon=gnome-pomodoro
[Icon Link](https://github.com/codito/gnome-pomodoro/blob/master/data/icons/256x256/gnome-pomodoro.png)

- [x] **pgAdmin 4**
Comment=PostgreSQL Tools
Icon=pgAdmin4
[Icon Link](https://user-images.githubusercontent.com/24623425/36042969-f87531d4-0d8a-11e8-9dee-e87ab8c6a9e3.png)

- [x] **Y Cutter**
Comment=Cut and Download Youtube Videos
Icon=chrome-opngmganjdbkepnmaakokoicipolgaeh-Default
[Icon Link](https://lh3.googleusercontent.com/DYRqBhUUeOCVTemngJl3Z6uJqq_Yi6k--45F8QsdErRTVvneybqP2PUU9A4VZenxXxq2=s180-rw)

- [x] **Wine Installer**
Icon=2402_msiexec.0
[Icon Link](https://cdn1.iconfinder.com/data/icons/Futurosoft%20Icons%200.5.2/128x128/apps/adept_installer.png)

**Comment by gusbemacbe** [comment]
Pronto, só não sei fazer ícone de Y Cutter.

@Bonandry, per favore, fai una icona di Y Cutter. Non so disegnare quest'icona.

**Comment by gusbemacbe** [comment]
Já sei fazer o de Y Cutter:

![y-cutter](https://user-images.githubusercontent.com/2257024/60024040-6ca70e80-966d-11e9-9207-dcdb101ec771.png)
