### ISSUE TITLE
Request Icon

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#21]
- [x] **Electron 4**
Icon=electron4
Icon Link: Crea una variante delle versioni Electron 2 ed Electron 3.

- [x] **Green Recorder**
Comment=Record your desktop easily using a simple GUI
Comment[it]=Registra facilmente il tuo desktop utilizzando una semplice GUI
Icon=green-recorder
Icon Link: Creare una variante con il colore verde dello screen recorder standard

- [x] **Code**  | **Editor di file sorgenti**
Comment=Edit code files
Comment[it]=Modifica file sorgenti
Icon=io.elementary.code
[Icon Link](https://github.com/elementary/code/blob/master/data/icons/64/io.elementary.code.svg)

- [x] **Mark Text**
Comment=Next generation markdown editor
Comment[it]=Editor markdown di prossima generazione
Icon=marktext
[Icon Link](https://github.com/marktext/marktext/blob/develop/resources/icons/md.svg)

---

Fixes:

- [x] **Insomnia**
@gusbemacbe Por favor, você poderia corrigir a cor do aplicativo `ìnsomnia` para o tom roxo ao invés do azul? Roxo é a verdadeira cor da aplicação e de sua interface. 

Obs: Eu percebi que os ícones do tema estão tendo uma tendência muito grande pela cor da azul, acho que está tendo um desequilibrio na paleta de cores.

![Captura de tela de 2019-07-07 00-31-07](https://user-images.githubusercontent.com/11943860/60763619-8a517c00-a04e-11e9-9e5a-e05e544f1339.png)

- [x] **PopCornTime**

O ícone da aplicação está faltando a pipoca que é seu simbolo.

it: L'icona dell'applicazione manca il popcorn che è il suo simbolo.

Original:

![16649342_627506480771472_4943160947962282020_n](https://user-images.githubusercontent.com/11943860/60763641-08ae1e00-a04f-11e9-9ae8-74baad5b3a1f.png)

Gnome Plus:

![Captura de tela de 2019-07-07 00-31-44](https://user-images.githubusercontent.com/11943860/60763627-a1906980-a04e-11e9-99fd-47b033983db4.png)

- [x] **Geary**

É possível dar um pouco mais de contraste à carta do ícone do `geary`? É um ícone feito pelo time do elementary OS, que aparentemente usou muito pouco contraste, que força a vista para identificar que dentro dele tem uma carta. Seria possível você aperfeiçoá-lo?

it: È possibile dare un po 'più di contrasto alla lettera delle icone' geary`? È un'icona creata dal team del sistema operativo elementare, che apparentemente utilizzava un contrasto molto piccolo, il che costringe la vista a identificare che al suo interno è presente una scheda. Sarebbe possibile per te perfezionarlo?

![Captura de tela de 2019-07-07 00-53-39](https://user-images.githubusercontent.com/11943860/60763796-fed9ea00-a051-11e9-909c-a7aaf257e039.png)

**Comment by gusbemacbe** [comment]
Oi @btd1337 

> Obs: Eu percebi que os ícones do tema estão tendo uma tendência muito grande pela cor da azul, acho que está tendo um desequilibrio na paleta de cores.

Verifica que as formas de roxo oficiais, produzidas pelos desenvolvedores do Projecto GNOME++, te parecem azul:

![image](https://user-images.githubusercontent.com/2257024/60763970-f5528100-a055-11e9-9dab-cfc72e595ce0.png)

> PopCornTime

Andrea utilizou a máscara na cabeça da pipoca. Eu já disse ao Andrea muitas vezes de não utilizar a máscara. Corrigi-lo-ei agora. 

> Geary

Testarei com as cores oficiais que dão mais contrastes.

**Comment by gusbemacbe** [comment]
Pronto, por favor, testa.

**Comment by btd1337** [comment]
@gusbemacbe O ícone do Popcorntime não foi alterado, ele continua com o mesmo problema.

Quanto ao ícone do Insomnia, o screeshot que eu tinha postado, é de uma versão que eu modifiquei com a cor roxa, a que estava antes no tema era azul. Mas já está corrigido.

**Comment by gusbemacbe** [comment]
Olá @btd1337 !

Por favor, transfere e testa: 

[popcorntime.zip](https://github.com/Bonandry/gnome-plus/files/3366404/popcorntime.zip)

**Comment by btd1337** [comment]
@gusbemacbe Há algo de errado com esse ícone e eu não sei dizer o que é. Veja que no Inkscape a pipoca aparece, mas pro restante do sistema não.

![Captura de tela de 2019-07-08 14-06-33](https://user-images.githubusercontent.com/11943860/60828916-13b99900-a18a-11e9-9bcb-1e6a9537b52c.png)

![Captura de tela de 2019-07-08 14-08-13](https://user-images.githubusercontent.com/11943860/60828926-1916e380-a18a-11e9-94c6-65a8d2f5509a.png)

**Comment by gusbemacbe** [comment]
Oi @btd1337 !

Exportei do Figma. Testa se o problema ainda insiste:

[popcorntime-2.zip](https://github.com/Bonandry/gnome-plus/files/3370369/popcorntime-2.zip)

**Comment by btd1337** [comment]
Agora está correto.

![Captura de tela de 2019-07-09 00-53-05](https://user-images.githubusercontent.com/11943860/60858307-206adb00-a1e4-11e9-88c9-5a1c5cb8accf.png)

![Captura de tela de 2019-07-09 00-54-20](https://user-images.githubusercontent.com/11943860/60858306-206adb00-a1e4-11e9-89d9-76cbb30eafe5.png)

**Comment by btd1337** [comment]
@gusbemacbe Com este ícone corrigido, pode adicioná-lo ao projeto e commitar a mudança para encerrar esta issue.

**Comment by gusbemacbe** [comment]
Pronto, @btd1337 . Desculpe-me, eu estava ocupado nessas semanas. Andrea não pode fazer agora, pois ele está trabalhando.

**Comment by btd1337** [comment]
@gusbemacbe O aplicativo `Green-Recorder` está com o ícone bugado na versão Dark. Veja a diferença:

**Gnome++**

![Captura de tela de 2019-07-16 03-13-20](https://user-images.githubusercontent.com/11943860/61270430-05fea780-a778-11e9-8597-074c9a17e363.png)

**Gnome++-Dark**

![Captura de tela de 2019-07-16 03-12-37](https://user-images.githubusercontent.com/11943860/61270447-1747b400-a778-11e9-9447-bf0e62a207a2.png)

**Comment by btd1337** [comment]
Green Recorder agora está ok.
