### ISSUE TITLE
Request Icons - Crow Translate Panel Indicators

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#22]
É possível criar os indicadores de painel que estão faltando para o aplicativo Crow Translate?

A requisição está bem detalhada nesta issue: https://github.com/zayronxio/Mojave-CT/issues/27

---

[IT] È possibile creare indicatori di dashboard mancanti per l'applicazione Crow Translate?

La richiesta è ben dettagliata qui: https://github.com/zayronxio/Mojave-CT/issues/27

**Comment by gusbemacbe** [comment]
Oi, @btd1337 !

Sim, é possível, os ícones estão localizados na pasta `actions` e `status`.

Fá-los-ei, pela manhã, pois Andrea faz só os ícones de aplicativos, de categorias, tipos de ficheiros e de pastas. Se Andrea quiser tentar, deixo-o fazê-los.

**Comment by gusbemacbe** [comment]
Pronto, por favor, testa, @btd1337 .

**Comment by btd1337** [comment]
Muito obrigado por mais este ótimo trabalho @gusbemacbe!
