### ISSUE TITLE
Request Icons: Kdenlive Interface Icons

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#23]
Seria possível adicionar [estes](https://github.com/TheDiveO/kdenlive-breeze-icons/tree/master/icons/actions) ícones da pasta `actions` que estão faltando na interface do Kdenlive?

[it] Sarebbe possibile aggiungere [queste](https://github.com/TheDiveO/kdenlive-breeze-icons/tree/master/icons/actions) icone dalla cartella `actions` che mancano nell'interfaccia di Kdenlive?

**ORIGINAL BREEZE ICONS**

![02 kdenlive19 04 1](https://user-images.githubusercontent.com/11943860/61187392-119e8100-a647-11e9-9f70-17254b20f31d.jpg)

**GNOME++ ICONS**

![Captura de tela de 2019-07-14 14-45-31](https://user-images.githubusercontent.com/11943860/61187425-54f8ef80-a647-11e9-8d47-724d1ec9e339.png)

**Comment by gusbemacbe** [comment]
Sim, é possível, mas tenho de redesenhar os ícones com a nova aparência do GNOME++. Tomarei alguns ícones do Papirus, pois a maioria dos ícones do Papirus são muito parecidos com os do Adwaita. 

Andrea informou-me que ele não pode fazer, pois ele está trabalhando nesta semana. Assumo o lugar dele.

**Comment by gusbemacbe** [comment]
Os ícones de Kdenlive estão quebrados. Terei de copiar os ícones do Papirus ao invés.

**Comment by gusbemacbe** [comment]
Previsão de `actions/16px` do Kdenlive:

![kdenlive-16px](https://user-images.githubusercontent.com/2257024/61190532-0f9ee700-a674-11e9-8fa5-3182577d9b47.png)

**Comment by gusbemacbe** [comment]
Pronto, @btd1337 !

**Comment by btd1337** [comment]
@gusbemacbe Eu não sei o porquê, mas não funcionou. Não sei se os ícones mudaram o nome, visto que aquele projeto tem 3 anos e foi esforço de um desenvolvedor em listar os ícones que a aplicação usava.

![Captura de tela de 2019-07-16 02-25-15](https://user-images.githubusercontent.com/11943860/61268165-0ba4bf00-a771-11e9-93dc-6d143d93f3fc.png)

**Comment by btd1337** [comment]
@gusbemacbe eu não sei o motivo, mas o tema Gnome++-Dark está com os ícones escuros, ao invés dos ícones claros.

![Captura de tela de 2019-07-16 02-53-36](https://user-images.githubusercontent.com/11943860/61269454-0184bf80-a775-11e9-9818-eb8fec22b07a.png)

**Comment by gusbemacbe** [comment]
Nesta imagem, o aplicativo está com os ícones do Breeze. GNOME++ está com novos ícones sem estilo do Breeze. É provável que tenhas aplicado o tema errado.

**Comment by btd1337** [comment]
O Gnome++ está selecionado, veja.

![Captura de tela de 2019-07-16 22-24-54](https://user-images.githubusercontent.com/11943860/61340432-a86e6780-a818-11e9-8052-bc223a8affe1.png)

**Comment by gusbemacbe** [comment]
Vou investigar. 

Já corrigi o ícone de Green Recorder. Por favor testa.

**Comment by btd1337** [comment]
@gusbemacbe o Green Recorder, inexplicavelmente continua com o mesmo bug apenas para a versão Dark do tema. Para a padrão e a Light o tema puxa o ícone com o fundo verde. Pro Dark ele está puxando a versão simbólica.

**Comment by gusbemacbe** [comment]
Estranho como vemos e analisamos na imagem:

![image](https://user-images.githubusercontent.com/2257024/61349704-67d41580-a83b-11e9-8518-cd44226472d1.png)

Acredito que o problema deve ser o `idnex.theme`

**Comment by gusbemacbe** [comment]
Ah, @btd1337, vê a imagem e tens de desabilitar "Force Breeze Icon Theme", então os ícones do Gnome++ Escuro apareceram normalmente:

![image](https://user-images.githubusercontent.com/2257024/61352890-df5a7280-a844-11e9-9510-7d7c1c7c80ef.png)

**Comment by gusbemacbe** [comment]
Por favor, testa com o ícone de Green Recorder.

**Comment by gusbemacbe** [comment]
E testa, desabilitando aquela opção e aplicando tema escuro, por favor.

**Comment by btd1337** [comment]
@gusbemacbe Veja: https://my.pcloud.com/publink/show?code=XZKbsG7ZF6vwuVtYorhbI1XBHSuUe4U2cmzX

Eu não entendo o motivo.

PS: Agora o Green Recorder está ok em todas as versões do tema.

**Comment by gusbemacbe** [comment]
Tu estás a utilizar Arch Linux GNOME? Como instalaste Kdenlive?

Ser-me-á útil que tu me contes os detalhes, pois testarei, investigarei e descobrirei este problema, porque Kdenlive instalado via apt funcionou com os ícones do GNOME++ aqui no meu Ubuntu 19.04.

**Comment by btd1337** [comment]
![Captura de tela de 2019-07-17 20-56-14](https://user-images.githubusercontent.com/11943860/61419604-5a6b6980-a8d5-11e9-81ef-3bcd065b3019.png)

**Comment by gusbemacbe** [comment]
Estranho, os ícones do GNOME++ funcionaram no Kdenlive no Arch Linux GNOME:

![image](https://user-images.githubusercontent.com/2257024/61445348-9fb68800-a923-11e9-8332-5347caf8fd2b.png)

Pode ser que tu aplicaste o tema de ícones no Qt5ct como eu vi no teu vídeo e QT5ct aplica os temas apenas aos aplicativos em KDE e QT, eu apliquei o tema de ícones com GNOME Tweaks. Entendi que os desenvolvedores do Kdenlive já desenvolveram uma versão GTK para Kdenlive. Por isso, tenta testar com GNOME Tweaks.

**Comment by btd1337** [comment]
Está perguntando se meu tema de ícones é o Gnome++? Se for, sim no meu sistema o tema ativo é o Gnome++.

**Comment by gusbemacbe** [comment]
Já sei que o GNOME++ está activo, mas acredito que o problema é Qt5c.

Em qual pasta colocaste o tema de ícones: `~/.icons` ou `~/.local/share/icons` ou `/usr/share/icons`?

**Comment by gusbemacbe** [comment]
Se testas e for mal-sucedido, vou perguntar no fórum Diolinux.

**Comment by btd1337** [comment]
Está como um link simbólico em `~/.icons`.

Tenho uma pasta que armazena todos os meus repositórios: `~/Repositorios`

Então aponto de lá para `~/.icons`

**Comment by gusbemacbe** [comment]
E tentaste aplicar com GNOME Tweaks e com KDE System Settings?

**Comment by btd1337** [comment]
@gusbemacbe este era o problema:

![Captura de tela de 2019-07-19 01-16-00](https://user-images.githubusercontent.com/11943860/61509857-e610f300-a9c6-11e9-938d-2a90d5c9f226.png)

**Comment by btd1337** [comment]
O tema Dark está faltando alguns ícones, veja:

**Gnome++**
![Captura de tela de 2019-07-19 01-48-35](https://user-images.githubusercontent.com/11943860/61510001-75b6a180-a9c7-11e9-927b-c2548daaa2dd.png)

**Gnome++Dark**
![Captura de tela de 2019-07-19 01-49-17](https://user-images.githubusercontent.com/11943860/61510033-8ebf5280-a9c7-11e9-8d2b-00128496b541.png)

**Comment by gusbemacbe** [comment]
Eu percebi que Andrea fez vários erros no tema de ícones. Eu tinha de recriar 4 milhares de ícones de `actions` com puro estilo do Adwaita. Reajustei as ligações simbólicas para reduzir e economizar o tamanho. Aderi os ícones perdidos do Papirus às pastas `actions` e `emblems`. Então eu corrigi o GNOME++ Escuro, retomando 4 mil ícones recriados e corrigidos do GNOME++. Eu também corrigi novamente as más configurações do `index.theme`, pois ele copiou o antigo `index.theme` mal configurado e bugado da antiga versão do tema de ícones Suru++ Ubuntu. 

Mas pronto, por favor, testa.

**Comment by btd1337** [comment]
Entendi,

Agora falta apenas estes ícones:

![Captura de tela de 2019-07-20 18-52-34](https://user-images.githubusercontent.com/11943860/61584533-a6115380-ab1f-11e9-8085-0c5d19f2fefe.png)

@gusbemacbe uma coisa que está estranha no sistema, é que alguns ícones usam a cor branco gelo (Padrão em temas escuros) e outros ícones usam um tom rosa claro.

É possível deixar todos usando apenas uma cor padrão?

Exemplo:

![Captura de tela de 2019-07-20 18-54-09](https://user-images.githubusercontent.com/11943860/61584545-f2f52a00-ab1f-11e9-94e2-8b75c5e0ac69.png)

![Captura de tela de 2019-07-20 18-54-01](https://user-images.githubusercontent.com/11943860/61584546-f2f52a00-ab1f-11e9-9c12-c222747085d4.png)

![Captura de tela de 2019-07-20 18-56-11](https://user-images.githubusercontent.com/11943860/61584554-17e99d00-ab20-11e9-80f1-933ab29a4b3b.png)

**Comment by gusbemacbe** [comment]
> É possível deixar todos usando apenas uma cor padrão?

Estranho, a maioria dos ícones no GNOME++ Escuro estão com a cor rosa clara. Acredito que por causa do Papirus instalado. 

Vou continuar a investigar. Andrea não devia ter copiado do Suru++ Ubuntu. Ele podia ter copiado do Papirus que não tem *bugs* e segue as regras do FreeDesktop. Na próxima vez que Andrea fizer um novo tema de ícones, pedi-lo-ei para ele copiar do Papirus, em vez de Suru++ Ubuntu, pois eu não passaria 3 meses, corrigindo os erros no tema de ícones.

**Comment by gusbemacbe** [comment]
Eu ia melhor o GNOME++ Escuro, mas eu ainda percebi vários erros no GNOME++. Já conversei com Andrea e pedi-lhe que ele não copiasse nada do Suru++ Ubuntu nem do Suru do Sam Hewitt.  

Eu tinha de reformar o tema inteiro e também de recriar milhares de ícones de todas as pastas, pois nele, ainda continha vários ícones do Suru++, e também tinha muitos ícones desnecessários colocados nas pastas erradas, por exemplo, vários ícones de música vindos da pasta `mimetypes` na pasta `status`. Melhorei o GNOME++ Escuro. Terminei.

Espero que funcione contigo. 

Uma coisa. Aviso-te que adicionei as novas cores de pastas, baseadas nas cores oficiais de Adwaita. Podes dar uma olhada na `places/scalable`. Observa que meu repositório Suru++ Pastas está desactualizado porque não actualizei os meus projectos por 3 meses, pois eu tinha de corrigir o GNOME++. Por isto, podes clonar meu repositório, modifica um pouco para mudar a cor de pastas do GNOME++.

**Comment by btd1337** [comment]
Apenas estes 2 ícones estão faltando no tema escuro:

![Captura de tela de 2019-07-30 19-52-18](https://user-images.githubusercontent.com/11943860/62170925-981fb780-b303-11e9-91b2-9553b2505a06.png)

![Captura de tela de 2019-07-30 19-52-07](https://user-images.githubusercontent.com/11943860/62170926-981fb780-b303-11e9-9e2a-4c9ea9df0b31.png)

**Comment by gusbemacbe** [comment]
Oi @btd1337,

Que frustrante, eu não esperava que o tema funcionasse. Vou investigar os ícones faltados, porque aquele tema de breeze-kdenlive não tem estes ícones, pois os ícones brancos de menu e de estrela já estão presentes no tema.

**Comment by gusbemacbe** [comment]
Hi @Pointedstick!

You are responsible for official Breeze icons theme, and working with KDE foundation. Do you recognise these two icons in Kdenlive? @TheDiveO's [kdenlive-breeze) has menu and star icons, but misses them which are present only in the Breeze icons theme

**Comment by Pointedstick** [comment]
The star icon is probably either `favorite`, `emblem-favorite`, `user-bookmarks-symbolic`, or `folder-favorite` (which would be an inappropriate use of that icon).

The menu icon I think is `kdenlive-menu`, which is probably worth a bug on KDenlive. They should be using the `application-menu` icon.

**Comment by gusbemacbe** [comment]
Hi @Pointedstick , thank you for indicating!

The `favorite` is missed. I fixed a bit the dirty codes. I undid the mistake that the author of the repo did — he added `application-menu` to `apps` instead of `actions` even if `application-menu` is already present in the folder `actions`.

I do not have `folder-favorite`, but I have `folder-favorites`.

@btd1337 , please test GNOME++ Dark. If the problem insists, I must remove `folder-favorites` and `kdenlive-menu` icons.

**Comment by btd1337** [comment]
Permanece

![Captura de tela de 2019-08-03 19-43-04](https://user-images.githubusercontent.com/11943860/62417472-f069f880-b626-11e9-87ac-b4f3927e9697.png)

![Captura de tela de 2019-08-03 19-44-32](https://user-images.githubusercontent.com/11943860/62417480-28713b80-b627-11e9-9aef-a4c2dbb10097.png)

**Comment by gusbemacbe** [comment]
Então são os ícones `folder-favorites` e `kdenlive-menu` que causam "bug" como @Pointedstick disse. Vou removê-los agora.

**Comment by gusbemacbe** [comment]
Primeiramente eu tinha de remover os ícones `kdenlive-menu` sem remover outros ícones `folder-favorites` para tu testares, @btd1337 .

Por favor, testa agora, @btd1337 . Caso o problema insista, o último ícone `folder-favorites` será removido.

**Comment by btd1337** [comment]
O ícone da estrela já tinha sido corrigido antes, então penso que não seja necessário mexer no ícone folder-favorites.

O problema é apenas com este ícone que parece o `view-list-details`.

**Comment by gusbemacbe** [comment]
Eu analisei os ícones de Papirus, concluí que o autor do projecto ligou os ícones errados. Vou corrigi-los.

**Comment by gusbemacbe** [comment]
Por favor, testa, @btd1337.

**Comment by btd1337** [comment]
Persiste.

**Comment by gusbemacbe** [comment]
@btd1337 , por favor, toca aquele ícone escuro, captura a etiqueta, copia a etiqueta aqui, por exemplo "Show...", pois estou a pesquisar no código-fonte de Kdenlive. 

```
LANGUAGE=en kdenlive
```

**Comment by gusbemacbe** [comment]
Parece-me que dois ícones `show-all-effects` e `kdenlive-custom-effect` são perdidos. Vou verificar no tema de ícones Breeze do @Pointedstick .

**Comment by gusbemacbe** [comment]
Finalmente achei o ícone perdido `show-all-effects` que está presente no tema de ícones Breeze do @Pointedstick ! Não está presente no Papirus nem no tema `kdenlive-breeze` do @TheDiveO. 

Veja, @btd1337, o ícone do Breeze: https://github.com/KDE/breeze-icons/blob/master/icons/actions/22/show-all-effects.svg

@SmartFinn, the `show-all-effects` icon is missed in your icons theme.

**Comment by gusbemacbe** [comment]
Pronto, por favor, testa, @btd1337 !

**Comment by btd1337** [comment]
@gusbemacbe Encontrou o ícone! Agora funcionou.

Eu penso apenas, que para manter o tema mais fiel ao projeto original, o ícone a ser escolhido deveria ser igual ao ícone `view-list-details.svg`

Veja:

`Breeze`

![Captura de tela de 2019-08-03 22-16-55](https://user-images.githubusercontent.com/11943860/62418334-ca4f5300-b63c-11e9-9fc6-7202dccb565a.png)


`Gnome++`

![Captura de tela de 2019-08-03 22-18-31](https://user-images.githubusercontent.com/11943860/62418338-d3d8bb00-b63c-11e9-8666-8a7ba9a8ec7e.png)

`view-list-details.svg`

![Captura de tela de 2019-08-03 22-21-20](https://user-images.githubusercontent.com/11943860/62418350-100c1b80-b63d-11e9-9bdc-6d15a0cf3f7c.png)

**Comment by gusbemacbe** [comment]
Excelente, @btd1337. O pesadelo acabou!

Vou actualizar o ícone. 

@Pointedstick and @SmartFinn, we have concluded that it was the missed icon `show-all-effects` present only in the Breeze icons theme, while not in the Papirus icons and in the outdated Kdenlive icons theme of TheDiveO.

@SmartFinn, please update your icons theme.

**Comment by gusbemacbe** [comment]
Pronto, @btd1337 ! Testa.

**Comment by btd1337** [comment]
@gusbemacbe funcionou para o ícone que estávamos falando, mas agora percebi que uma das suas últimas mudanças apagou um outro ícone que fica perto da saída de vídeo. O ícone de opções. Veja:

`Breeze`

![Captura de tela de 2019-08-03 22-57-24](https://user-images.githubusercontent.com/11943860/62418576-a989fc00-b642-11e9-8749-21dbf32f2974.png)
`
Gnome++`

![Captura de tela de 2019-08-03 22-59-33](https://user-images.githubusercontent.com/11943860/62418581-b149a080-b642-11e9-82c5-463c9fbf201c.png)

Este sim deve ser o ícone de menu que você tinha usado antes:

![62418338-d3d8bb00-b63c-11e9-8666-8a7ba9a8ec7e](https://user-images.githubusercontent.com/11943860/62418585-d211f600-b642-11e9-944e-7999c3d3eb1a.png)

**Comment by gusbemacbe** [comment]
Vou usar o código-fonte de Kdenlive para rastejar o nome do ícone.

**Comment by gusbemacbe** [comment]
Ah, encontrei no `kdenlive-18.12.3a/src/effectstack/widgets/animationwidget.cpp`:


```cpp
    QToolButton *menuButton = new QToolButton;
    menuButton->setIcon(KoIconUtils::themedIcon(QStringLiteral("kdenlive-menu")));
    menuButton->setToolTip(i18n("Options"));
    menuButton->setMenu(container);
    menuButton->setPopupMode(QToolButton::InstantPopup);
    tb->addWidget(menuButton);
```

Então é o `kdenlive-menu` que removi. Vou restaurá-lo.

**Comment by gusbemacbe** [comment]
Desculpe-me pela demora, @btd1337 . É que eu fui notificado pelo jogo Star Trek Timelines que a viagem chegou ao dilema e eu tinha de completá-lo. Tinha de ficar atentivo ao esgotamento de antimatéria. Mas acabei de actualizar.

**Comment by btd1337** [comment]
Agora tudo está Ok. Muito obrigado, @gusbemacbe !

![Captura de tela de 2019-08-04 19-11-04](https://user-images.githubusercontent.com/11943860/62429906-b31b6e80-b6eb-11e9-9842-14136b8053fe.png)

**Comment by gusbemacbe** [comment]
Muito obrigado, finalmente terminei. O pesadelo acabou. O autor do projecto prometeu-me que ele não vai copiar nada do Suru++ Ubuntu nem misturar os ícones de temas diferentes. Para novos temas, ele utilizará o Papirus do @SmartFinn. 

Já conversei com o autor, propondo uma sugestão. Desde que GNOME++ é derivado do Dawaita, renomearemos para Adwaita++. O que achas, @btd1337 ?

**Comment by btd1337** [comment]
Achei uma ótima sugestão. Fará bastante sentido!
