### ISSUE TITLE
Request Icons

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#24]
- [x] **Regex Tester**
Comment=Testing regular expressions
Icon=com.github.artemanufrij.regextester
[Icon Link](https://github.com/artemanufrij/regextester/blob/master/data/icons/64/com.github.artemanufrij.regextester.svg)

- [x] **Reco**
Comment=Record talks to remember the contents later
Icon=com.github.ryonakano.reco
[Icon Link](https://github.com/ryonakano/reco/blob/master/data/icons/128/com.github.ryonakano.reco.svg)

- [x] **VidCutter**
Comment=the simplest + fastest video cutter & joiner
Icon=com.ozmartians.VidCutter
[Icon Link](https://github.com/ozmartian/vidcutter/blob/master/data/icons/hicolor/128x128/apps/com.ozmartians.VidCutter.png)

- [x] **Sigil**
Comment=ePUB file editor
Icon=sigil
[Icon Link](https://www.macupdate.com/images/icons256/33395.png)

**Comment by gusbemacbe** [comment]
Pronto, @btd1337 !

**Comment by btd1337** [comment]
Muito obrigado novamente por esse excelente trabalho @gusbemacbe!
