### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#27]
- [x] **astah UML**
Comment=UML modeling tool with Mind Mapping
Icon=astah_uml.png
[Icon Link](https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/cd/bd/03/cdbd038d-72e2-62ba-5082-c3a70045ce97/pr_source.png/1200x630wa.png)

- [x] **Planner**
Comment=Never worry about forgetting things again
Icon=com.github.alainm23.planner
[Icon Link](https://github.com/alainm23/planner/blob/master/data/icons/128/com.github.alainm23.planner.svg)

- [x] **Rush**
Comment=Time manager app to break your work into intervals to keep you focused.
Icon=com.github.naaando.rush
[Icon Link](https://github.com/naaando/rush/blob/master/data/icons/128/com.github.naaando.rush.png)

- [x] **Figma**
Comment=The collaborative interface design tool.
Icon=/usr/share/pixmaps/figma.png
[Icon Link](https://cdn-images-1.medium.com/max/1600/1*6XgfDCVn81AYX68Xvd2I-g@2x.png)

- [x] **GCleaner**
Comment=A Cleaner for the GNU/Linux Operating System
Icon=gcleaner
[Icon Link](https://github.com/gcleaner/gcleaner-vala/blob/master/data/icons/128/gcleaner.svg)

- [x] **Modelio**
Comment=The opensource modeling environment
Icon=/opt/modelio/icon.xpm
[Icon Link](https://www.modelio.org/images/stories/logo-modelio-128x128.png)

**Comment by Bonandry** [comment]
Fatte, nella versione PRIVATE

l'icona figma è già presente
l'icona modelio l'ho fatta ma non sono convinto che funzioni

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

OK, vado fonderle. Per l'icona di Modelio, l'hai rinominata "modelio" o "icon"?

@btd1337, temos de colocar o nome de `modelio` ao invés de `icon`.

**Comment by Bonandry** [comment]
modelio

**Comment by gusbemacbe** [comment]
OK, tutto risolto. Vado fonderle.

**Comment by btd1337** [comment]
@gusbemacbe Apenas informando que os ícones foram incluídos diretamente na Branch Master e ainda não foram mergeados na Branch Beta.

**Comment by gusbemacbe** [comment]
Puxa, eu me esqueci de trocar de branch antes de fundi-la.

**Comment by gusbemacbe** [comment]
Pronto, vou ter de ficar atentivo à branch antes de fundir a branch beta do privado ao pùblico.

**Comment by btd1337** [comment]
@gusbemacbe conhendo o seu padrão de organização, imaginei que algo tivesse passado desapercebido, por isso vim notificar. Obrigado mais uma vez! (y)
