### ISSUE TITLE
Adwaita has no size field

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#29]
Command:

`journalctl -b -p warning -n 50 --no-hostname`

Output:

```
set 11 23:58:23 firefox[2015]: Theme directory status/48 of theme Adwaita++-Dark has no size field
set 11 23:58:23 firefox[2015]: Theme directory status/48@2x of theme Adwaita++-Dark has no size field
set 12 00:03:57 gedit[32529]: Theme directory status/48 of theme Adwaita++-Dark has no size field
set 12 00:03:57 gedit[32529]: Theme directory status/48@2x of theme Adwaita++-Dark has no size field
set 12 00:20:06 gnome-shell[1453]: Theme directory status/48 of theme Adwaita++-Dark has no size field
set 12 00:20:06 gnome-shell[1453]: Theme directory status/48@2x of theme Adwaita++-Dark has no size field
set 12 00:20:20 gnome-terminal-[20255]: Theme directory status/48 of theme Adwaita++-Dark has no size field
set 12 00:20:20 gnome-terminal-[20255]: Theme directory status/48@2x of theme Adwaita++-Dark has no size field
set 12 00:21:39 gnome-shell[1453]: Theme directory status/48 of theme Adwaita++-Dark has no size field
set 12 00:21:39 gnome-shell[1453]: Theme directory status/48@2x of theme Adwaita++-Dark has no size field
set 12 00:21:42 gnome-terminal-[20255]: Theme directory status/48 of theme Adwaita++-Dark has no size field
set 12 00:21:42 gnome-terminal-[20255]: Theme directory status/48@2x of theme Adwaita++-Dark has no size field
set 12 00:27:19 gnome-shell[1453]: Theme directory status/48 of theme Adwaita++-Dark has no size field
set 12 00:27:19 gnome-shell[1453]: Theme directory status/48@2x of theme Adwaita++-Dark has no size field
```

Solution:

https://forums.mydigitallife.net/threads/gtk-warning-theme-directory-of-theme-oxygen-has-no-size-field-solved.75856/

**Comment by gusbemacbe** [comment]
Oi @btd1337 !

Os `[status/48]` e `[status/48@2x]` estão ausentes. Aderi-los-ei hoje pela tarde.

@Bonandry 

Per favore, non toccare il file `index.theme` del tema `Adwaita++ Scuro`! Perché non sei un analista di sistema, programmatore e analista di *test*. Lascialo a me! Grazie per la comprensione!

**Comment by Bonandry** [comment]
@gusbemacbe 
non mi sembra di averlo mai toccato, non capisco

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

Lo so, hai mai toccato, ma solo un consiglio.

**Comment by gusbemacbe** [comment]
Aconteceram erros sérios, @btd1337 .

O italiano copiou muitos ícones desnecessários do Suru/Yaru para o Adwaita++ na pasta `status`. Muitos ícones não estão a seguir o estio de Adwaita. Ele não devia fazer isto. Indicarei os ícones impuros a ele para ele corrigir.

Só não afectou o Adwaita++ Escuro. Vou utilizar o Meld para comparar os ícones perdidos e descartar os ícones indesejados e desnecessários. Serei cauteloso.

**Comment by gusbemacbe** [comment]
Puxou, eles copiou acidentalmente os ícones simbólicos na pasta `16`.

**Comment by gusbemacbe** [comment]
Por favor, testa se a nova versão *beta* resolveu o problema de «no size field», @btd1337.

**Comment by gusbemacbe** [comment]
Como testaste e disseste que o problema foi resolvido, fecharei agora.
