### ISSUE TITLE
Migliorare le icone

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/gnome-plus#3]
Ciao @Bonandry !

Credo che devi migliorare alcune icone:

<p><img align="middle" alt="disco solido" height="64px" src="https://raw.githubusercontent.com/Bonandry/gnome-plus/master/GNOME%2B%2B/devices/scalable/drive-harddisk-solidstate.svg?sanitize=true"> drive-harddisk-solidstate.svg </p>

* Le icone di disco rigido e disco solido non devono essere stesse, perché il disco rigido è molto vecchio e il solido è molto nuovo. 
* I dischi rigido e solido sono differenti. La differenza tra essi;
  * il rigido è lento e prende più di 30 secondi d'avvio. Il computer sempre è lento con un rigido;
  * il solido è rapidamente e prende tra 1 millisecondo e 5 secondi d'avvio. Il computer sempre è animato e rapido con un solido;

Ti mostrerò l'icona di disco solido del mio Suru++:

<img alt="disco solido" height="64px" src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/devices/64/drive-harddisk-solidstate.svg?sanitize=true">

Sull'internet, compara le icone:

* [Visualizza l'immagine di disco rigido](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.ictcart.com%2F91%2Fseagate-2tb-hard-disk-drive.jpg&f=1)
* [Visualizza l'immagine di disco solido](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fae01.alicdn.com%2Fkf%2FHTB1dpn9aC_I8KJjy0Foq6yFnVXaJ%2FHard-drive-disk-128GB-256GB-512GB-ssd-hard-drive-ssd-64G-32GB-16GB-8GB-solid-state.jpg&f=1)

Alcune icono sono troppo realistiche per il GNOME++:

<p><img align="middle" alt="USB" height="64px" src="https://raw.githubusercontent.com/Bonandry/gnome-plus/master/GNOME%2B%2B/devices/scalable/drive-removable-media-usb.svg?sanitize=true"> drive-removable-media-usb.svg </p>

<p><img align="middle" alt="tablet" height="64px" src="https://raw.githubusercontent.com/Bonandry/gnome-plus/master/GNOME%2B%2B/devices/scalable/input-tablet.svg?sanitize=true">  input-tablet.svg  </p>
<p><img align="middle" alt="flash"  height="64px" src="https://raw.githubusercontent.com/Bonandry/gnome-plus/master/GNOME%2B%2B/devices/scalable/media-flash.svg?sanitize=true">   media-flash.svg   </p>
<p><img align="middle" alt="CD"     height="64px" src="https://raw.githubusercontent.com/Bonandry/gnome-plus/master/GNOME%2B%2B/devices/scalable/media-optical.svg?sanitize=true"> media-optical.svg </p>

Andiamo alla cartella «prova mines» che ho analisato, ma ho alcuni suggerimenti:

* L'icona `libreoffice-web` deve riempire il intero rettangolo arrotondato con un carta geografia e cambia di nero per azzuro. 
* L'icona `shellscript` non è un'applicazione come un `.exe`, è un *script* o compilatore. L'icona corretta è quella del tema di icone Papirus:

<img alt="text-x-script" height="64px" src="https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/Papirus/64x64/mimetypes/text-x-script.svg?sanitize=true">

**Comment by gusbemacbe** [comment]
Anche credo che le icone d'archiviazione di `mimetypes` anche devono migliorare. Ti raccomando di aggiungere l'abbreviazione, ad esempio, "apk" all'icona di `application-apk`.

**Comment by gusbemacbe** [comment]
Per favore, vai alla cartella `icone-generiche/applicazioni/monocromatico` e vedi le icone colorite che hai dimenticato d'aggiungere alle cartelle `16` e `scalable` di `apps`.

**Comment by gusbemacbe** [comment]
Fa attenzione all'email del Travis sulla tua e-mail! Solamente non vado raccontare cosa sta succedendo. Scopre a te stesso!

**Comment by gusbemacbe** [comment]
Le icone di archiviazione di `mimetypes` devono utilizzare l'icona bianca, altra icona (nera) è per `apps`. Per non confondere `apps` con `mimetypes`. 

![image](https://user-images.githubusercontent.com/2257024/56460803-f50fe700-637e-11e9-8194-3dc933bc4e4d.png)

Quest'icona è incorretta. PHP non è una pagina di web, è un file di testo di linguaggio di programmazione PHP:

![image](https://user-images.githubusercontent.com/2257024/56460812-17a20000-637f-11e9-987f-c001c6cff378.png)

Per favore fa' attenzione sulle email di Travis!

**Comment by gusbemacbe** [comment]
Anche altra icona è incorretta. "x-theme" è per i file `.theme`, che sono file di tema di icone e di GTK:

![image](https://user-images.githubusercontent.com/2257024/56460847-b62e6100-637f-11e9-8f42-868c68f27982.png)

Più altra incona incorretta, "trash" significa spazzatura;

![image](https://user-images.githubusercontent.com/2257024/56460861-eaa21d00-637f-11e9-8821-169b1d71d575.png)

HTML, malgrado di una pagina di web, è un file di testo di linguaggio di programmazione:

![image](https://user-images.githubusercontent.com/2257024/56460885-3b197a80-6380-11e9-8f6d-2debcb813cfe.png)

**Comment by Bonandry** [comment]
> Le icone di archiviazione di `mimetypes` devono utilizzare l'icona bianca, altra icona (nera) è per `apps`. Per non confondere `apps` con `mimetypes`.
> 
> ![image](https://user-images.githubusercontent.com/2257024/56460803-f50fe700-637e-11e9-8194-3dc933bc4e4d.png)

non ho capito

**Comment by Bonandry** [comment]
> Per favore, vai alla cartella `icone-generiche/applicazioni/monocromatico` e vedi le icone colorite che hai dimenticato d'aggiungere alle cartelle `16` e `scalable` di `apps`.

ho controllato, molte icone sono presenti

**Comment by gusbemacbe** [comment]
@Bonandry 

Applica l'icona `application-x-archive.svg` per tutte le icone d'archiviazione sulla cartella `mimetypes/scalable` perché quell'icona nera è solamente per la cartella `apps/scalable`, perche gli utenti possono essere confusi con queste icone se le icone d'archiviazione delle cartelle `apps` e `mimetypes` sono stesse.

**Comment by gusbemacbe** [comment]
> ho controllato, molte icone sono presenti

Ma le vecchie icone colorite non sono presenti sulle cartelle `16` e `scalable` della cartella `apps`. Vado ne copiarle per le cartelle che vai capire.

**Comment by gusbemacbe** [comment]
Pronto, controlla le vecchie icone sulle cartelle `16` e `scalable` della `apps`.

**Comment by Bonandry** [comment]
> @Bonandry
> 
> Applica l'icona `application-x-archive.svg` per tutte le icone d'archiviazione sulla cartella `mimetypes/scalable` perché quell'icona nera è solamente per la cartella `apps/scalable`, perche gli utenti possono essere confusi con queste icone se le icone d'archiviazione delle cartelle `apps` e `mimetypes` sono stesse.

quindi elimino Zip, Rar ecc?

**Comment by gusbemacbe** [comment]
Non, non eliminare, copia le icone d'archiviazione (apk, rar, zip, ecc.) della cartella `icone-generiche/tipo di file multimediale/colorito`.

**Comment by Bonandry** [comment]
@gusbemacbe l'icona scrivania come ti piace? 

![Schermata da 2019-04-21 22-35-11](https://user-images.githubusercontent.com/7957697/56475265-1dced400-6486-11e9-983c-848aab8d3efb.png)
![Schermata da 2019-04-21 22-36-09](https://user-images.githubusercontent.com/7957697/56475266-1dced400-6486-11e9-992b-8937d53c4fec.png)

**Comment by gusbemacbe** [comment]
La seconda. Se io voglio la prima, la scrivania deve avere poche colori senza sfumatura.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry , ho aggiunto alcune icone perdute di tipi di file multimediale, vedi la descrizione. Loro sono già allo stile di GNOME 3.32, ma devi cambiare i colori, perché i miei colori sono molto cyberpunk e non so quali colori stai utilizzando.

**Comment by Bonandry** [comment]
Ciao @gusbemacbe 
ho ricolorato le icone multimediale
ho ridisegnato gli emblem
ho cambiato gli scheenshot
ho messo in generiche sette colorazioni di user-desktop

una domanda, cosa manca per poterlo pubblicare?

**Comment by gusbemacbe** [comment]
Ciao @Bonandry,

Utiliza il Meld per comparare e copiare tutte le icone perdute di `mimetypes` de mio Suru++25 (beta) (scaricare col commando: `git clone -b beta --single-branch https://github.com/gusbemacbe/suru-plus`) per la cartella `mimetypes` di GNOME++ e di Suru++ Ubuntu.

**Comment by Bonandry** [comment]
si le ho viste, secondo me sono troppe e non tutte molto utili, rimango con queste

**Comment by gusbemacbe** [comment]
OK, @Bonandry, senza problemi, farò per te se alcune sono importanti. Oggi vado rivedere, se alcune icone hanno bisogno migliorare. 

Dopo farò presentazioni e articoli per il tuo tema di icone.

**Comment by Bonandry** [comment]
ok grazie

**Comment by gusbemacbe** [comment]
L'icona di Dropbox è troppo vecchia e classica. Modernizzala e ricolora on i di GNOME 3.32.

**Comment by Bonandry** [comment]
ok

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Gli sviluppatori di GNOME utilizzano molto le maschere nell'icone.

Per favore, studia le icone deformate se utilizzi il Dolphin:

![image](https://user-images.githubusercontent.com/2257024/56507956-5b207980-64f9-11e9-9b0c-4c7014105025.png)

**Comment by gusbemacbe** [comment]
Le icone di Firefox sono troppo realistiche per il GNOME 3.32. Lo stile di GNOME è molto **semplificato** senza sfumature avanziate, riflesso realistico e ombra realistica:

![image](https://user-images.githubusercontent.com/2257024/56508191-fade0780-64f9-11e9-8541-9f43a931f9ea.png)

**Comment by gusbemacbe** [comment]
L'icona di Git deve essere ridesgnata e ricolorata con i colori di GNOME 3.32:

![image](https://user-images.githubusercontent.com/2257024/56508264-25c85b80-64fa-11e9-901b-0385e07678cb.png)

**Comment by gusbemacbe** [comment]
Quest'icona ha bisogno di essere ridesgnata e migliore, perché essa è troppo classica:

![image](https://user-images.githubusercontent.com/2257024/56508394-835ca800-64fa-11e9-9d8c-c5228e682561.png)

**Comment by gusbemacbe** [comment]
Rendila meno Suru++ e più GNOME 3.32:

![image](https://user-images.githubusercontent.com/2257024/56508698-578df200-64fb-11e9-999c-0aad0421a39b.png)

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Ho aggiunto le icone **importanti** alla cartella `mimetypes`. Per favore, rivedi, collega, ridesgna e ricolora.

**Comment by Bonandry** [comment]
non riesco a togliere la maschera all'icona web-browser
clicco su togli maschera ma non succede niente

**Comment by gusbemacbe** [comment]
Vado fare per te. So come risolvere questi bug, perché ho studiato molto come risolvere tutti i bug sul mio tema Suru++ 25.

**Comment by Bonandry** [comment]
quando puoi cerca di spiegarmelo

**Comment by gusbemacbe** [comment]
Ecco il video:

https://vimeo.com/user31062576/review/331813783/5336bdc1d9

**Comment by gusbemacbe** [comment]
Ecco il risultato:

![image](https://user-images.githubusercontent.com/2257024/56511659-827c4400-6503-11e9-92b8-d795a430b18f.png)

**Comment by Bonandry** [comment]
si vedono ancora delle sfumature, comunque ottimo

**Comment by gusbemacbe** [comment]
Sì, le sfumature eranno mascherate. Perciò, ecco il risultato finale:

![image](https://user-images.githubusercontent.com/2257024/56511883-24039580-6504-11e9-8026-c06c40a161e9.png)

**Comment by gusbemacbe** [comment]
Per favore utilizza il Dolphin, per verificare se le icone sono deformate o non.

**Comment by Bonandry** [comment]
ho provato ma non visualizzo le icone con dolphin

**Comment by gusbemacbe** [comment]
Andiamo al TeamViewer, @Bonandry ?

**Comment by Bonandry** [comment]
fatte tutte !!
