### ISSUE TITLE
Some icons not rendering in Gnome 3.34

### ISSUE THREAD

**Issue by filipkemuel** [Bonandry/gnome-plus#30]
Many icons are no longer rendering after I updated to Gnome Shell 3.34.

SVG-rendering in 3.34 must have changed or something like that because the icons are simply rendered blank. 

Opening all the affected svg's in Inkscape and saving them back solves the issue. After that they render properly. However that Is quite time consuming and I still do not know why those icons were not rendering before.

Most of the icons for the "stock" Gnome apps are affected and many, many toolbar icons (including close) and the "Show Applications" icon. But also many others.

**Comment by gusbemacbe** [comment]
Hi @filipkemuel !

It is a `share-mime-info`'s bug as @btd1337 has indicated us at the Yaru++ icons issue. See the reference: https://bugzilla.redhat.com/show_bug.cgi?id=1751549.

You must downgrade to the version 1.12.

If you do not want to downgrade to `share-mime-info`'s previous version, the icons theme will be ready this week. I am still working on optimising the icons theme with SVG Cleaner to fix the bugs of `share-mime-info`, as @btd1337 has recommended us.

**Comment by gusbemacbe** [comment]
Hello @filipkemuel !

The icons theme is ready, but I need you to test if it works on your OS. Download here: https://send.firefox.com/download/1c2e010ff9f1269e/#IEDynD9MlNJUfmLE-WyC8w.

**Comment by filipkemuel** [comment]
Hi @gusbemacbe 

Thanks for the info. I downloaded and tested the theme. It works quite well and so far all the icons seems to have been fixed.

I'm on Arch BTW

**Comment by gusbemacbe** [comment]
Great, many Arch users had this problem with this icons theme due to the latest `share-mime-info` version. 

I am also an Arch user, but with KDE. The icons theme author is only an Ubuntu user. 

As it is solved, the issue will be closed. I will push from the private repo to this repo today or tomorrow.
