### ISSUE TITLE
 Adwaita++ has no size field (English please)

### ISSUE THREAD

**Issue by lb-d** [Bonandry/gnome-plus#31]
(darktable:9472): Gtk-WARNING **: 11:21:05.676: Theme directory status/48 of theme Adwaita++ has no size field

(darktable:9472): Gtk-WARNING **: 11:21:05.676: Theme directory status/48@2x of theme Adwaita++ has no size field

(darktable:9472): Gtk-WARNING **: 11:21:10.465: Theme directory status/48 of theme Adwaita++ has no size field

(darktable:9472): Gtk-WARNING **: 11:21:10.465: Theme directory status/48@2x of theme Adwaita++ has no size field

**Comment by gusbemacbe** [comment]
Hi @lb-d !

I have just released a new beta version. Please download and test the beta branch, and see if it fixed the size field.

**Comment by gusbemacbe** [comment]
In reference to #29, the problem has been issued and solved.
