### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by btd1337** [Bonandry/gnome-plus#32]
- [x] **GHex**  | **Editor Esadecimale**
Comment=Inspect and edit binary files
Icon=org.gnome.GHex
[Icon Link](https://gitlab.gnome.org/GNOME/ghex/blob/master/icons/hicolor/256x256/apps/org.gnome.GHex.png)

- [x] **Nibbles**
Comment=Guide a worm around a maze
Comment[it]=Guida un verme in giro per un labirinto
Icon=org.gnome.Nibbles
[Icon Link](https://gitlab.gnome.org/GNOME/gnome-nibbles/tree/master/data/icons/hicolor)

- [x] **Iagno**  | **Reversi**
Comment=Dominate the board in a classic version of Reversi
Comment[it]=Domina la tavola in una versione classica di Reversi
Icon=org.gnome.Reversi
[Icon Link](https://gitlab.gnome.org/GNOME/iagno/blob/master/data/icons/hicolor/256x256/org.gnome.Reversi.png)

- [x] **Postman**
Comment=Build, test, and document your APIs faster
Icon=postman
[Icon Link](https://miro.medium.com/max/512/1*fVBL9mtLJmHIH6YpU7WvHQ.png)

- [x] **Rocket.Chat**
Comment=Rocket.Chat Native Cross-Platform Desktop Application via Electron.
Icon=rocketchat-desktop
[Icon Link](https://github.com/RocketChat/Rocket.Chat/blob/develop/public/images/logo/icon.svg)

**Comment by Bonandry** [comment]
#32 OK

**Comment by btd1337** [comment]
What branch are the icons on?

**Comment by gusbemacbe** [comment]
@btd1337 

They are in the private repo. I will send the compressed file to you at Telegram.

Andrea is working on redesigning the battery icons.

**Comment by btd1337** [comment]
Right. Just waiting for the changes to be made available here.

**Comment by gusbemacbe** [comment]
REady, @btd1337 .

Added icons and redesigned battery icons.
