### ISSUE TITLE
Firefox Icons

### ISSUE THREAD

**Issue by Noxellar** [Bonandry/gnome-plus#33]
I'd like to draw to your attention that an icon that you are using for Firefox on your README.md file is misleading. The firefox-2019.svg file does not look like the one that is displayed in the Adwaita++/apps/scalable files. The file that is in there looks more like the firefox-2019-gnome-plus.svg file.

It'd be nice if you could change the ones in the files to the one displayed in the README.md please

**Comment by gusbemacbe** [comment]
Hello @xenoxriar 

The icon `firefox-2019.svg` does not have a black circle, `firefox-2019-gnome-plus.svg` has a black circle.

If you use the dark desktop environment, both icons seem the same.

**Comment by Noxellar** [comment]
I meant the colours of the firefox icons are different to the ones in the README.md file
![image](https://user-images.githubusercontent.com/32978806/70703096-7dceff00-1d23-11ea-9055-9e0cb192a155.png)
The image in the files
![image](https://user-images.githubusercontent.com/32978806/70703168-a22adb80-1d23-11ea-8227-f3acc59332b3.png)
The image as shown

**Comment by gusbemacbe** [comment]
@xenoxriar 

It is solved in the branch `beta`. Sorry for my absence. The project author refused to make more than 3 thousands icons he deleted accidentally. I had to take his place and remake all 3k icons.
