### ISSUE TITLE
Battery icon is fuzzy

### ISSUE THREAD

**Issue by dac73** [Bonandry/gnome-plus#35]
![image](https://user-images.githubusercontent.com/20690019/75232598-c8ef9e80-57b7-11ea-856b-a836b10a4a7f.png)
Resolution: 1920x1200
Gnome: 3.34

**Comment by gusbemacbe** [comment]
Hello @dac73 !

Thank you for reporting.

I who redesigned the battery icons, assigned myself for this.

@Bonandry, per favore, NON ridisegnare le icone di batteria. Io cho le ho ridisegnate. Lascia che me ne occupi io. 

@btd1337 and @DarthWound

:gb: Please check if the icon also seems fuzzy for your computer.
:brazil: Por favor verifiques se o ícone te parece desfocado no teu compuatdor.

**Comment by gusbemacbe** [comment]
@dac73 

I understood that your monitor is Full HD. I will verify the folders.

**Comment by ghost** [comment]
@gusbemacbe 

Sorry I don't have any laptop, so I can't test. But as I said in #34 they redesigned the battery status icons in 3.34 maybe look at that. Looks like @dac73 uses an extension to show battery percentage, maybe it alters the icon too, ask him to try without extensions in order to troubleshoot.

_PS: 1920x1200 isn't Full HD though, Full HD is 1920x1080. But it shouldn't matter here._

**Comment by dac73** [comment]
It's the same on 1080p, also without percentage (which is set in gnome-tweaks).
![image](https://user-images.githubusercontent.com/20690019/75259551-7e3a4a80-57e8-11ea-8538-f9e53fb453ff.png)
Gnome shell theme is default.

**Comment by drakkai** [comment]
![Screenshot from 2021-04-03 16-10-46](https://user-images.githubusercontent.com/2467051/113480937-354ad000-9497-11eb-9e80-89880267fde9.png)
the problem still exists and only with battery icon
resolution: 1600x900
gnome: 3.38.5

**Comment by gusbemacbe** [comment]
@Drakkai 

What was the battery percent?

**Comment by gusbemacbe** [comment]
Please, @dac73, @DarthWound and @Drakkai, test it.

**Comment by drakkai** [comment]
![Screenshot from 2021-04-13 20-10-33](https://user-images.githubusercontent.com/2467051/114600510-b7f03e00-9c94-11eb-802c-0ca481984bae.png)
After update looks the same.

**Comment by gusbemacbe** [comment]
@Drakkai, strange, these icons are based on @SmartFinn's Papirus status battery icons.

@SmartFinn, analyse my battery design on Figma and select `staus/16px` page: https://www.figma.com/file/CaWjKZMjgPEFaUmPEfIz94O2/Adwaita-Part-1?node-id=32%3A2

**Comment by SmartFinn** [comment]
@gusbemacbe the icons should be 16px instead 48px. That why they are blurred.

**Comment by gusbemacbe** [comment]
> @gusbemacbe the icons should be 16px instead 48px. That why they are blurred.

But they used to be 16px before and they were still fuzzy. I understood that fuzzy means blurry.

**Comment by gusbemacbe** [comment]
I found the problems, I'll follow the standard Papirus battery icons, @SmartFinn and @Drakkai.

- Adwaita++ doesn't have `panel/{16,22,24}` that Papirus does. 
- Adwaita does not have 22px and 24px battery icons in the `status folder`
- Comparing the Papirus battery icons, the Adwaita++ battery icons are wrong. 

I will create a new folder `panel` and redevelop or redesign the Papirus battery icons in the Adwaita++ style.

**Comment by gusbemacbe** [comment]
Please, test, using the branch `beta`, @Drakkai, Use `Adwaita++` (not `Adwaita++-Dark`, and observe that battery icons are already white) and verify if it works for you.

If it works, I'll redesign cautiously the icons, following the standard Papirus battery icons.

**Comment by drakkai** [comment]
I've installed beta version with below command but it looks more like the default Adwaita.
```
wget -qO- https://raw.githubusercontent.com/Bonandry/adwaita-plus/beta/install.sh | TAG=beta sh
```
![Screenshot from 2021-04-20 20-08-52](https://user-images.githubusercontent.com/2467051/115444538-f9dd2f00-a214-11eb-9d53-77bfdb87cd5e.png)

**Comment by gusbemacbe** [comment]
Do you mean the panel, @Drakkai? 

In the window, the icons look more like Papirus icons.

**Comment by drakkai** [comment]
I mean the battery icon, but you may be right it's more like Papirus icon.

**Comment by gusbemacbe** [comment]
Please, can you test @SmartFinn's Papirus icon theme to see if the icon on the panel appears more like Papirus icon and if it's not buggy?

**Comment by drakkai** [comment]
Papirus icon: 
![Screenshot from 2021-04-23 21-40-23](https://user-images.githubusercontent.com/2467051/115922065-b2f17280-a47c-11eb-9bf6-3a51eb2b5a85.png)

**Comment by gusbemacbe** [comment]
Yes, I'll study it.

**Comment by gusbemacbe** [comment]
Hello @Drakkai 

Please, test "Adwaita++" from the branch `beta`:

[Adwaita++.zip](https://github.com/Bonandry/adwaita-plus/files/6449094/Adwaita%2B%2B.zip)

**Comment by drakkai** [comment]
this is what the icon looks like
![Screenshot from 2021-05-12 22-16-42](https://user-images.githubusercontent.com/2467051/118039650-d9fede00-b370-11eb-8ba0-251001491777.png)

**Comment by gusbemacbe** [comment]
Then the Papirus battery icons worked, does it seem buggy for you?

**Comment by gusbemacbe** [comment]
Hello @Drakkai 

Now you can test the new version of Adwaita++ and Adwaita++ Dark. Report if it is still buggy. Just say me it is still bug or it is solved.

If you like the new design, I will close the thread. If you prefer the horizontal icon, I will make an alternative pack.

**Comment by drakkai** [comment]
Both versions look fine. Vertical design is OK :)

**Comment by gusbemacbe** [comment]
Great! I am going to close.
