### ISSUE TITLE
Dolphin funziona con successo sull'Ubuntu. Ti preparo un tutorial. 

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/gnome-plus#4]
Ciao @Bonandry !

In questa schermata, l'anteprima di immagini sul Dolphin, sull'Ubuntu 19.04, (ma anche è uguale in 18.04). In questa schermata, È possibile vedere le icone deformate (ad esempio, "aiuto.svg").

![Dolphin sull'Ubuntu](https://user-images.githubusercontent.com/2257024/56547839-e844ec00-6554-11e9-82e3-38f26039ad62.png)

Vado prepararti un tutorial...

1. Apri il «Ubuntu Software»;
2. Cerca «Dolphin» e seleziona «Rimuovi»

![Dolphin sull'Ubuntu 2](https://user-images.githubusercontent.com/2257024/56548108-9486d280-6555-11e9-90bf-1e47e6bc05b6.png)

3. Chiude l'applicazione. Apri il terminale. Esegui il commando:

```bash
sudo apt update && sudo apt upgrade && sudo apt install dolphin
```

4. Riavvia. 
5. Apri il Dolphin e vedi se l'anteprima di immagini funziona.

Se funziona, se vuoi aggiungere Dolphin ai preferiti del pannello, apri il terminale ed esegui:

```bash
sudo gedit /usr/share/applications/org.kde.dolphin.desktop
```

Gedit aprirà il file di configurazione di desktop del Dolphin. Aggiungi l'opzione `StartupWMClass=dolphin` alla fine del file. Salvalo. E esegui il commando:

```bash
sudo update-desktop-database 
```

Adesso puoi aggiungere il Dolphin ai preferiti. :-)

**Comment by Bonandry** [comment]
Grazie Gustavo, vorrei che fosse Nautilus il preferito per aprire i file e usare Dolphin solo per visualizzare le icone

**Comment by Bonandry** [comment]
![Schermata da 2019-04-23 07-46-18](https://user-images.githubusercontent.com/7957697/56557663-392c0300-659c-11e9-9937-cbcc45fd97f7.png)

niente, sempre uguale

**Comment by gusbemacbe** [comment]
@Bonandry ,

Hai fatto correttamente ed esattamente cosa io ti ho istruito?

**Comment by Bonandry** [comment]
si
disinstallato dal software centre
sudo apt update && sudo apt upgrade && sudo apt install dolphin
riavviato e ti ho fatto la schermata

p.s. ho corretto l'icona "aiuto"

**Comment by gusbemacbe** [comment]
@Bonandry, strano, deve essere a causa del 18.04. Vado interrompere il mio lavoro per testare, utilizzando la versione 18.04 invece di 19.04.

**Comment by Bonandry** [comment]
non ti preoccupare, dimmi se ci sono icone sbagliate e vedo di rifarle

**Comment by gusbemacbe** [comment]
OK, ecco le icone:

![image](https://user-images.githubusercontent.com/2257024/56559921-64512b00-6579-11e9-84aa-e94b051e3122.png)

![image](https://user-images.githubusercontent.com/2257024/56559952-792dbe80-6579-11e9-9187-30a295f5affc.png)

![image](https://user-images.githubusercontent.com/2257024/56559968-82b72680-6579-11e9-9b92-7a06976fb91b.png)

![image](https://user-images.githubusercontent.com/2257024/56559995-9498c980-6579-11e9-85ae-ef0379a91e2a.png)

![image](https://user-images.githubusercontent.com/2257024/56560004-9febf500-6579-11e9-9328-1a4adf21b56d.png)

![image](https://user-images.githubusercontent.com/2257024/56560027-af6b3e00-6579-11e9-907b-e1928375fa5b.png)

![image](https://user-images.githubusercontent.com/2257024/56560033-bb570000-6579-11e9-9741-2b762776b339.png)

![image](https://user-images.githubusercontent.com/2257024/56560054-c7db5880-6579-11e9-8d58-984bbe243831.png)

![image](https://user-images.githubusercontent.com/2257024/56560069-d295ed80-6579-11e9-92c3-51caa3e5104d.png)

![image](https://user-images.githubusercontent.com/2257024/56560083-dcb7ec00-6579-11e9-9ead-427fa402465a.png)

![image](https://user-images.githubusercontent.com/2257024/56560104-eb9e9e80-6579-11e9-85cd-fd1d4dbdefc3.png)

![image](https://user-images.githubusercontent.com/2257024/56560132-ffe29b80-6579-11e9-9070-0a9598105bcb.png)

![image](https://user-images.githubusercontent.com/2257024/56560148-0c66f400-657a-11e9-8a34-6c98e57fd0bc.png)

![image](https://user-images.githubusercontent.com/2257024/56560172-14bf2f00-657a-11e9-96d5-42fbe291de62.png)

![image](https://user-images.githubusercontent.com/2257024/56560186-1f79c400-657a-11e9-8aef-5cc48cdc2ac7.png)

![image](https://user-images.githubusercontent.com/2257024/56560205-27d1ff00-657a-11e9-95ec-a3fb78aa5f72.png)

![image](https://user-images.githubusercontent.com/2257024/56560224-328c9400-657a-11e9-8e65-fbd515f4f2f0.png)

![image](https://user-images.githubusercontent.com/2257024/56560237-3b7d6580-657a-11e9-9154-ac00ee1c4381.png)

**Comment by Bonandry** [comment]
forse ho risolto
controlla la cartella BUG

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

Poche icone stano ancora con bug (cronologia.svg, editore-di-testo.svg, google-chrome.svg, ricerca.svg, thunderbirds.svg e traduttore.svg):

![image](https://user-images.githubusercontent.com/2257024/56570447-5dcead80-6591-11e9-898c-8975eff7b3f6.png)

**Comment by Bonandry** [comment]
ho fatto un altra prova, ci sono due versioni di chrome e un altra di Thunderbird
l'icone buggate di chrome tìhunderbird erano quelle originali

**Comment by gusbemacbe** [comment]
Oggi notte vedo. Io sono senza internet e telefono.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Felicitazioni, tuttu sta risolto. Solamente un pochetto nell'icona di Google Chrome 2. 

![image](https://user-images.githubusercontent.com/2257024/56611650-a9607600-65e8-11e9-9140-a8b42b87230f.png)

**Comment by gusbemacbe** [comment]
Ciao @Bonandry,

Ci sono icone deformate sulla cartella `mimetypes`:

![image](https://user-images.githubusercontent.com/2257024/56611787-13791b00-65e9-11e9-8959-f4f1bab6664a.png)

![image](https://user-images.githubusercontent.com/2257024/56611865-46231380-65e9-11e9-82df-bcf0617e7d8f.png)

L'icona sta sbagliata. Non è un'icona di citazioni, è un'icona di referenze bibliografiche:

![image](https://user-images.githubusercontent.com/2257024/56611933-6f43a400-65e9-11e9-9a46-04c723cab7eb.png)

L'icona anche sta sbagliata. Non è un'icona di testo. È un'icona di tema di icone e de GTK/KDE;

![image](https://user-images.githubusercontent.com/2257024/56612012-9d28e880-65e9-11e9-9264-f5afa078b161.png)

**Comment by gusbemacbe** [comment]
Sulla cartella `apps`, ho risolto l'icona di web-browser, ma queste icone deformate sono collegate all'icona di Ephiphany invece di web-browser:

![image](https://user-images.githubusercontent.com/2257024/56612326-76b77d00-65ea-11e9-9fe8-23e4ed1aa4f7.png)

**Comment by gusbemacbe** [comment]
Ho già risolto gli sbagliati di Ephiphany e le ho ricollegate all'icona di web-browser.

**Comment by Bonandry** [comment]
ciao @gusbemacbe ho caricato le icone corrette nella cartella BUG

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Tutto sta risolto. Solamente un pochetto nell'icona di Google Chrome. Hai dimenticato di rimuover la copia. :-p 

![image](https://user-images.githubusercontent.com/2257024/56614957-876af180-65f0-11e9-9205-1c6361bc5288.png)

**Comment by Bonandry** [comment]
ricaricato chrome .... io ODIO le maschere :D

**Comment by gusbemacbe** [comment]
Perfetto e tutto sta risolto, senza, @Bonandry ! Felicitazioni!

Sì, gli sviluppatori hanno fatto un grande sbagliato.

Gli utenti dei gestori di file Dolphin, PCFM, Krunner, Krusader e Polo, dei gestori di pannello – Docky, Latte Dock e Plank, e di KDE saranno felici con il tuo lavoro.

Sì, la prossima volta, quando vuoi fare nuove icone, è migliore disegnare **in forma** e **senza maschera**, che tutto funzionerà in tutti gli ambienti grafici. Questo è il mio segreto di come io ho studiato e risolto i *bug* in KDE quando siamo stati di accordo di dividere i nostri temi delle icone.

Come sai sapere disegnare senza maschera, poi hai già scoperto il mio segreto, finalmente puoi aggiungere le icone di non-GNOME ai tuoi temi di icone, **senza paura**. 

Se non sei sicuro se l'icona ha una maschera, è facile verificare per mezzo del simbolo nella lista di layers/oggetti:  ![image](https://user-images.githubusercontent.com/2257024/56616353-91daba80-65f3-11e9-803f-12356c9675fa.png)
