### ISSUE TITLE
Firefox nightly icon

### ISSUE THREAD

**Issue by sergioad** [Bonandry/gnome-plus#40]
Hello, could you add an icon for Firefox nightly and a firefox-nightly-2019-mozilla variant?

From Ubuntu
icon=firefox-trunk

**Comment by Bonandry** [comment]
![Schermata da 2021-04-21 11-35-43](https://user-images.githubusercontent.com/7957697/115532135-ce4e5900-a295-11eb-94cf-94efd03990c9.png)

**Comment by Bonandry** [comment]
[firefox-nightly.zip](https://github.com/Bonandry/adwaita-plus/files/6349763/firefox-nightly.zip)

**Comment by sergioad** [comment]
Thanks

**Comment by sergioad** [comment]
I would recommend  to add a symlink of firefox-nightly to firefox-trunk for Ubuntu users; BTW when you think the icons will land into the  beta?

PS: I prefer all the way the icon in which firefox-2019-mozilla is based to the original Firefox logo, it is way more modern and elegant, it is a shame Mozilla has not updated  the app logos to it

**Comment by Bonandry** [comment]
trunk already exists, it will be placed in the beta version

**Comment by gusbemacbe** [comment]
The `firefox-trunk` icon depends on the `firefox` icon. You have to symlink manually it. 

Or the another easier solution: copy the Firefox Nightly desktop file from `/usr/share/applications` to `~/.local/share/applications`, and modify `Icon=firefox-trunk` to `Icon=firefox-nightly`. Run three times `update-desktop-database` on the terminal.

**Comment by sergioad** [comment]
Ok, thanks

**Comment by gusbemacbe** [comment]
¡Hola @sergioad!

El icono de Firefox Nightly fue agregado a la branch `beta` y el README fue actualizado para nuevos surgimientos de como cambiar fácilmente de icono alternativo.

**Comment by sergioad** [comment]
Te lo agradezco mucho
