### ISSUE TITLE
Colorful and colorful-dark themes incomplete in some apps

### ISSUE THREAD

**Issue by sith-on-mars** [Bonandry/gnome-plus#41]
I find colorful and colorful-dark themes are bit incomplete. Here is an example in Okular:

Dark: 
![4](https://user-images.githubusercontent.com/37974764/116906215-803f3b00-ac2f-11eb-985b-4e4fe9959dd5.png)

Dark: colorful:
![5](https://user-images.githubusercontent.com/37974764/116906227-8208fe80-ac2f-11eb-9a27-5d735b39627a.png)

**Comment by gusbemacbe** [comment]
Hello, @sith-on-mars, can you test Adwaita++ and Adwaita++ Dark (without Colourful) if they are complete?

**Comment by sith-on-mars** [comment]
Hey! I think Adwaita++ and Adwaita++ Dark are complete. Actually, the first screenshot is from Adwaita++ Dark.

**Comment by gusbemacbe** [comment]
I got to understand that Dark Colourful is incomplete. I'll investigate tonight.

**Comment by gusbemacbe** [comment]
I found the issues. The Adwaita++ Colorful Dark has wrong symlinks, and some icons are lost. I am working on it today.

**Comment by gusbemacbe** [comment]
Please, @sith-on-mars , test.

**Comment by sith-on-mars** [comment]
It seems that the icons in the new beta version no longer respect dark mode.

This is the beta "dark colorful" in Okular:
![1](https://user-images.githubusercontent.com/37974764/118412173-1475bd00-b688-11eb-928a-60c128b67f1e.png)

Here are few more examples:

The stable version of "dark colorful" in Transmission:
![2](https://user-images.githubusercontent.com/37974764/118412218-4ab33c80-b688-11eb-83cb-d058c302cf5b.png)

The beta version of "dark colorful" in Transmission:
![4](https://user-images.githubusercontent.com/37974764/118412296-bbf2ef80-b688-11eb-9e9c-e0b075b6a4ba.png)

The stable version of "dark colorful" in Audacious: 
![3](https://user-images.githubusercontent.com/37974764/118412246-76362700-b688-11eb-8665-d1b7807d6f4f.png)

The beta version of "dark colorful" in Audacious
![5](https://user-images.githubusercontent.com/37974764/118412335-e5138000-b688-11eb-8ac2-91e20b454877.png)

**Comment by gusbemacbe** [comment]
I noticed that, at the file `index.theme` of Adwaita++ Dark Colourful inherited the wrong icon theme... from Adwaita++. I am going to fix it.

**Comment by gusbemacbe** [comment]
Fixed and done. Please test again.

**Comment by sith-on-mars** [comment]
Now the problem is fixed! The icons in the apps I mentioned above (Okular,  Transmission and Audacious) now look the same between the dark version and the dark-colorful version. Thank you very much for this!

By the way, what's the differences between dark theme and the dark-colorful theme? They almost look the same to me.

**Comment by gusbemacbe** [comment]
> By the way, what's the differences between dark theme and the dark-colorful theme? They almost look the same to me.

In the Adwaita++ Dark, 16px apps, mimetypes and places icons are monochromatic. In the Adwaita++ Dark Colourful, the 16px to 32px apps, mimetypes and places icons are colourful.
