### ISSUE TITLE
12 icone perdute

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/gnome-plus#42]
Ciao @Bonandry 

Ho aggiunto le tue ultime icone alla branch `beta, adesso fa queste icone perdute:

- [x] **Buho (Applicazione di Maui Project)**
Icona = buho

![imagem](https://user-images.githubusercontent.com/2257024/117603801-52279280-b12a-11eb-8a63-f7dcab66ff65.png)

- [x] **Clip (Applicazione di Maui Project)**
Icona: clip

![imagem](https://user-images.githubusercontent.com/2257024/117604015-bba7a100-b12a-11eb-87cb-df830d602f5c.png)

- [x] **Communicator (Applicazione di Maui Project)**
Icona: communicator

![imagem](https://user-images.githubusercontent.com/2257024/117604094-e3970480-b12a-11eb-9d72-4faf1a29ab22.png)

- [x] **Icon Requests**
Icona: icon-requests

![imagem](https://user-images.githubusercontent.com/2257024/117603052-87cb7c00-b128-11eb-9d7a-ac62ef4b476a.png)

- [x] **Index (applicazione di Maui Project)**
Icona: index

![imagem](https://user-images.githubusercontent.com/2257024/117603658-0bd23380-b12a-11eb-8233-71daf85a1c20.png)

- [x] **Neo4j Desktop**
Icona: neo4j-desktop

![imagem](https://user-images.githubusercontent.com/2257024/117603076-94e86b00-b128-11eb-9417-c6812d831370.png)

- [x] **Nota (Applicazione di Maui Project)**
Icona: maui-nota

![imagem](https://user-images.githubusercontent.com/2257024/117604170-10e3b280-b12b-11eb-9ccf-372451314752.png)

- [x] **Pix (Applicazione di Maui Project)**
Icona: maui-pix

![imagem](https://user-images.githubusercontent.com/2257024/117604271-5a340200-b12b-11eb-8de6-573a07814894.png)

- [x] **Redis Desktop Manager**
Icona: rdm

![imagem](https://user-images.githubusercontent.com/2257024/117603131-b9444780-b128-11eb-8205-1cef5af5f564.png)

- [x] **Shelf (Applicazione di Maui Project)**
Icona: shelf

![imagem](https://user-images.githubusercontent.com/2257024/117604228-383a7f80-b12b-11eb-831d-d0ddafd7ed09.png)

- [x] **Studio 3T Linux**
Icona: Studio-3T (senza spazzatura)

![i4j_extf_6_kzs8aq_1ytw8nz](https://user-images.githubusercontent.com/2257024/117603290-163ffd80-b129-11eb-8a9d-86702a7a15fa.png)

- [x] **Zoom**
Icona: Zoom

![imagem](https://user-images.githubusercontent.com/2257024/117603198-e4c73200-b128-11eb-9e97-4ff49362d75d.png)

**Comment by Bonandry** [comment]
Fatte
