### ISSUE TITLE
libadwaita folder icons

### ISSUE THREAD

**Issue by FlyinPancake** [Bonandry/gnome-plus#48]
Since Gnome 42 folder icons are blue instead of the beige. Are you going to stick to beige or will you switch to blue since now that is the official adwaita look?

Thanks in advance :smile:

**Comment by gusbemacbe** [comment]
Good morning, @JamesL813!

As I am overcharged with my employment job as a software engineer, I can't solve it, but do you know doing it?

**Comment by JamesL813** [comment]
@gusbemacbe I'd be happy to take a look and see if I can!

**Comment by gusbemacbe** [comment]
@JamesL813, yes, please, thank you.

**Comment by gusbemacbe** [comment]
Done, @FlyinPancake. Merged. It's in the branch `beta`.

**Comment by FlyinPancake** [comment]
Thanks @gusbemacbe and @JamesL813  you're both awesome 😄

**Comment by FlyinPancake** [comment]
![image](https://user-images.githubusercontent.com/36113055/164968307-9996f272-5a95-434d-95df-2c64782128b7.png)
Looking :fire:
