### ISSUE TITLE
Aggiunte icone importanti alle cartelle «apps» e «mimetypes»

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/gnome-plus#5]
Ciao @Bonandry !

Ho ricevuto molte nuove icone venute di Papirus. Ho aggiunto icone importante alla cartella `mimetypes`, come nei casi di tipo di file di *comic book*, libro di scifi, le estensioni di immagini di Windows, come `bitmap` e `ico`, e i tipi di Kdenlive, nuovi collegamenti di Krita, ecc.

Per favore, rivide, ridisegna e ricolora. 

E non dimenticare di copiare le icone perdute di `scalable` per `16`.

**Comment by gusbemacbe** [comment]
E anche ho aggiunto molte icone importanti alla cartella `apps` per completare, che gli utenti non vanno troppo richiederti molte icone.

**Comment by Bonandry** [comment]
Ciao @gusbemacbe 
- ho eliminato la cartella BUG
- ho eliminato le nuove icone da fare e l'ho salvate in una cartella apposita
- molte icone non le ho fatte perche sono già buone quelle di default 
- 800 icone da fare richiedono troppo tempo direi di farle solo su richiesta dell'utente 
- propongo di rilasciare il set e di rentegrarle nel tempo

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

OK, senza problema. Ti piacerebbe che io ridisegnassi le icone della cartella «da fare»?

**Comment by gusbemacbe** [comment]
Muove indietro il logo di Debian a quel luogo:

![image](https://user-images.githubusercontent.com/2257024/56692564-dbd9a400-66b8-11e9-8ad1-3b829131b7b1.png)

**Comment by Bonandry** [comment]
> Ciao @Bonandry !
> 
> OK, senza problema. Ti piacerebbe che io ridisegnassi le icone della cartella «da fare»?

certo!!

**Comment by Bonandry** [comment]
> Muove indietro il logo di Debian a quel luogo:
> 
> ![image](https://user-images.githubusercontent.com/2257024/56692564-dbd9a400-66b8-11e9-8ad1-3b829131b7b1.png)

non ho capito come ti piacerebbe, io il logo lo volevo eliminare

**Comment by gusbemacbe** [comment]
> non ho capito come ti piacerebbe, io il logo lo volevo eliminare

Non, non eliminare il logo né l'abbreviazione. Mantenili. 

Solamente muovi il logo per la posizione antica e originale come hai visto sull'antica icona.

**Comment by Bonandry** [comment]
added goobox
change DEB
ricolorato le icone piccole da 4d4d4d a 241f31 come nella palette di gnome

**Comment by gusbemacbe** [comment]
> ricolorato le icone piccole da 4d4d4d a 241f31 come nella palette di gnome

Poche icone non sono colorate. Vado correggerle.

**Comment by gusbemacbe** [comment]
Corretto e fatto, @Bonandry

**Comment by gusbemacbe** [comment]
@Bonandry , hai bisogno di ridisegnare le icone di `status` con le differenti saturazioni del stesso colore.

**Comment by gusbemacbe** [comment]
@Bonandry !

Quest'icona è troppo realistica e c'è un strano oggetto:

![image](https://user-images.githubusercontent.com/2257024/56764082-443c8a00-677a-11e9-9a39-588f700889de.png)

**Comment by gusbemacbe** [comment]
L'icona di Firefox è troppo realistica. Imita l'icona di Thunderbird;

![image](https://user-images.githubusercontent.com/2257024/56764168-7ea62700-677a-11e9-9afd-e2d420769d8b.png)

**Comment by gusbemacbe** [comment]
Senza bordo, per favore:

![image](https://user-images.githubusercontent.com/2257024/56764238-a4333080-677a-11e9-9479-1b1875c4771f.png)

**Comment by Bonandry** [comment]
firefox è l'icona originale, non dovrei neanche metterla ma se non la metto non funziona la piccola (16)

**Comment by gusbemacbe** [comment]
Ho ottimizzato le icone, ma le icone stano con cosa strana:

![image](https://user-images.githubusercontent.com/2257024/56768196-10666200-6784-11e9-8662-19c75216ed29.png)

Converti il bordo in oggetto:

![image](https://user-images.githubusercontent.com/2257024/56768459-cf228200-6784-11e9-8209-beee9dd43bb1.png)


> firefox è l'icona originale, non dovrei neanche metterla ma se non la metto non funziona la piccola (16)

È probabile che hai installato Firefox tramite Flatpak o Snap. Flatpak o Snap non sono compatibili con qualsiasi tema di icone, perché esse utilizzano il **percorso predefinito** delle icone. Perciò, hai bisogno di editare manualmente i file `.desktop`. Vedi la wiki del Suru++ Ubuntu in italiano:

* [Suru++ Ubuntu – App installate tramite Snap](https://github.com/Bonandry/suru-plus-ubuntu/wiki/App-create-tramite-Snap)
* [Suru++ Ubuntu – Icone predefinite delle app con un nome brutto](https://github.com/Bonandry/suru-plus-ubuntu/wiki/Icone-predefinite-delle-app-con-un-nome-brutto)

**Comment by gusbemacbe** [comment]
Ho corretto il bug dell'icona di `google-earth.svg`, rimuovendo l'immagine incorporata e i codici sporchi di filtri e gradienti non utilizzati del SVG.

**Comment by Bonandry** [comment]
Firefox è quello di default, oggi pomeriggio, quando torno dal lavoro, correggo le due icone

**Comment by gusbemacbe** [comment]
> Firefox è quello di default

Va alla cartella `/usr/share/applications/` e trova `firefox.desktop`. Aprilo con l'editore di testo, copia tutto e incola qui.

**Comment by Bonandry** [comment]
Exec=firefox %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=firefox
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
Actions=new-window;new-private-window;

**Comment by Bonandry** [comment]
ho corretto:
comix
file
pdfslicer
geogebra

ho cambiato:
rete
energia

ho aggiunto:
vim
gvim
org.gnome.Keysign
affinity-designer
anjuta
xchat
zenkit
zipper
youtube
youtube-dl
application-3D
xcos
vivaldi-beta
corebird
polly
xnsketch
fofix
google-agenda
google-photos
google-webdesigner
google-play-music-desktop
cairo-dock
cantata
xnview
xournal
jdownloader
griffith
nuvolapalyer
aegisub
calamares
deezer
ekiga
im-ekiga
masterpdfeditor5
master-pdf-editor
masterpdfeditor
org.stellarium.Stellarium
squid
stellarium

**Comment by Bonandry** [comment]
added 
cairo-dock 
cantata 
xnview 
xournal

**Comment by gusbemacbe** [comment]
> Exec=firefox %u
> Terminal=false
> X-MultipleArgs=false
> Type=Application
> Icon=firefox
> Categories=GNOME;GTK;Network;WebBrowser;
> MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
> StartupNotify=true
> Actions=new-window;new-private-window;

Ah, essa non sta utilizzando il percorso assoluto/codificato. Ma fa un backup dell'icona, crea una icona fantasiosa e testa.

**Comment by gusbemacbe** [comment]
Senza buco:

![image](https://user-images.githubusercontent.com/2257024/56868567-5f053d80-69ca-11e9-8bb5-d2b23bd95fbf.png)

**Comment by Bonandry** [comment]
fatta

**Comment by gusbemacbe** [comment]
Migliore adesso, @Bonandry !

Hai finito tutto o ancora sta mancando? Se hai finito tutto, vado scrivere il README.

**Comment by Bonandry** [comment]
io direi di pubblicare, poi con calma o su richiesta facciamo le mancanti

**Comment by gusbemacbe** [comment]
OK, vado scrivere, ma il README sta incompleto. Anche ho bisogno di creare le immagini per il tuo OpenDesktop. 

Crea due immagini sull'Inkscape, con la risoluzione 1440 x 1080 e dipinge con la sfumatura con i colori aranciato di Ubuntu e porpora di Canonical. Esporta 60 icone di «apps» che chiamano più l'attenzione degli utenti e fa una griglia da 10 x 6 in un'immagine. E nell'altra immagini, esporta 10 (10 x 1) icone di «devices» e 20 (10 x 2) di «mimetypes». Non utilizzare le icone già originali e esistenti del tema di icona originale Adawita.

**Comment by Bonandry** [comment]
non ho capito niente... ma ci provo :D

**Comment by gusbemacbe** [comment]
OK, vado esplicare facilmente. 

Prima immagine
1. Crea l'immagine di 1440x1080 sull'Inscape e applicala la sfumatura con i colori di aranciato e porpora;
2. Copia 60 icone di «apps/scalable» (senza le icone originali);
3. Organizza le 60 icone in 10 (verticalmente ) x 6 (orizzontalmente);

Seconda immagine:
1. Crea l'immagine di 1440x1080 sull'Inscape e applicala la sfumatura con i colori di aranciato e porpora;
2. Crea il testo "Devices";
3. Copia 10 icone di «devices/scalable» (senza le icone originali);
4. Organizza le 10 icone in 10 (verticalmente ) x 1 (orizzontalmente);
5. Crea il testo "Mimetypes";
6. Copia 20 icone di «mimetypes/scalable» (senza le icone originali);
7. Organizza le 20 icone in 10 (verticalmente ) x 2 (orizzontalmente);

Osserva che copia queste icone **che attira molta attenzione degli utenti**.

**Comment by Bonandry** [comment]
device non ci sono 10 icone e sono tutte derivate dal set gnome

**Comment by gusbemacbe** [comment]
> device non ci sono 10 icone e sono tutte derivate dal set gnome

Sì, ma le icone di disco solido e di Thundebrolt non sono originali. Inventa le nuove 8 icone di dispositivi. Da un'occhiata alla cartella del mio Suru++: [«Suru++/devices/scalable/»](https://github.com/gusbemacbe/suru-plus/tree/beta/Suru%2B%2B/devices/scalable) e vedi se alcune di esse non esistono nella tua cartella.

**Comment by Bonandry** [comment]
fatte e caricate, vado a preparare le immagini

**Comment by Bonandry** [comment]
come si caricano le 60 icone , una a una ?

**Comment by gusbemacbe** [comment]
@Bonandry 

1. Sul Nautilus, seleziona le 60 icone.
2. Trascinale e non le rilasciare, poi trascinale fino all'Inkscape;
3. Sull'Inkscape, rilasciale.

**Comment by gusbemacbe** [comment]
O puoi vedere facilmente l'esempio in GIF:

![Peek 2019-04-28 17-02](https://user-images.githubusercontent.com/2257024/56869463-8b738680-69d7-11e9-82ac-31b97f91397a.gif)

**Comment by Bonandry** [comment]
le ho caricate in IMAGES

**Comment by gusbemacbe** [comment]
Perfetto, vado scrivere il README e il prodotto sul tuo OpenDesktop. 

Vai a letto adesso? Se sì, vado prendre cura del tuo tema, OK?

**Comment by Bonandry** [comment]
Si Gustavo domani al lavoro, ciao

Il dom 28 apr 2019, 23:13 Gustavo Reis <notifications@github.com> ha
scritto:

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Ho finito il tuo repositorio e di scrivere il tuo prodotto sull'OpenDesktop. Non editare l'OpenDesktop, perché l'edizione del prodotto dell'OpenDesktop ha un bug di loop infinitivo. 

Andiamo creare la nuova branch/versione con il nome `beta`, ma ti consiglio di creare il repositorio privato `beta` perché mi sembra che loro hanno rubato le mie idee del mio Suru++ (ad esempio, gradienti delle miei cartelle, Avengers, Star Trek e Star Wars). :-(
