### ISSUE TITLE
How to change directories icons to blue?

### ISSUE THREAD

**Issue by joaquincorradi** [Bonandry/gnome-plus#52]
How can I change the directories icons to the blue ones or any other color? Changing to _"Adwaita++-Colorful"_  doesnt's do anything.

![Captura desde 2022-07-22 16-52-44__01](https://user-images.githubusercontent.com/53107439/180517861-6edca178-74a2-4122-8200-67d0e275184d.png)

**Comment by gusbemacbe** [comment]
Hello @joaquincorradi 

You can use Suru++ Folders to modify Adwaita++ folders colour. Adwaita++ is listed on Suru++ Folders script:

As you are Spanish-speaking person, I added the language path to ease your job:

https://gusbemacbe.github.io/suru-plus-folders/es/

**Comment by joaquincorradi** [comment]
> Hello @joaquincorradi
> 
> You can use Suru++ Folders to modify Adwaita++ folders colour. Adwaita++ is listed on Suru++ Folders script:
> 
> As you are Spanish-speaking person, I added the language path to ease your job:
> 
> https://gusbemacbe.github.io/suru-plus-folders/es/

That's really helpful. Thank you so much!!
