### ISSUE TITLE
CURSORE

### ISSUE THREAD

**Issue by Bonandry** [Bonandry/gnome-plus#6]
The cursor.theme and index.theme files says Suru as name? 

abbiamo lasciato il nome SURU al cursore

**Comment by gusbemacbe** [comment]
Ciao@Bonandry,

Per favore correggi ciòe sostituisce il nome.

Dovrebbe rivedere tutto prima di pubblicare, poi gli utenti hanno già installato il tuo tema di icone prima dei tuoi aggiornamenti.

**Comment by Bonandry** [comment]
io propongo di lasciare il suo nome dato che non abbiamo fatto nessuna modifica

**Comment by gusbemacbe** [comment]
OK, @Bonandry !

Se l'utente viene a lamentarse, andiamo analizzare, OK?
